# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: applicationclient_protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Security_pb2
import yarn_service_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='applicationclient_protocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n applicationclient_protocol.proto\x12\x0bhadoop.yarn\x1a\x0eSecurity.proto\x1a\x19yarn_service_protos.proto2\xe0\n\n ApplicationClientProtocolService\x12l\n\x11getNewApplication\x12*.hadoop.yarn.GetNewApplicationRequestProto\x1a+.hadoop.yarn.GetNewApplicationResponseProto\x12u\n\x14getApplicationReport\x12-.hadoop.yarn.GetApplicationReportRequestProto\x1a..hadoop.yarn.GetApplicationReportResponseProto\x12l\n\x11submitApplication\x12*.hadoop.yarn.SubmitApplicationRequestProto\x1a+.hadoop.yarn.SubmitApplicationResponseProto\x12k\n\x14\x66orceKillApplication\x12(.hadoop.yarn.KillApplicationRequestProto\x1a).hadoop.yarn.KillApplicationResponseProto\x12l\n\x11getClusterMetrics\x12*.hadoop.yarn.GetClusterMetricsRequestProto\x1a+.hadoop.yarn.GetClusterMetricsResponseProto\x12\x66\n\x0fgetApplications\x12(.hadoop.yarn.GetApplicationsRequestProto\x1a).hadoop.yarn.GetApplicationsResponseProto\x12\x66\n\x0fgetClusterNodes\x12(.hadoop.yarn.GetClusterNodesRequestProto\x1a).hadoop.yarn.GetClusterNodesResponseProto\x12]\n\x0cgetQueueInfo\x12%.hadoop.yarn.GetQueueInfoRequestProto\x1a&.hadoop.yarn.GetQueueInfoResponseProto\x12q\n\x10getQueueUserAcls\x12-.hadoop.yarn.GetQueueUserAclsInfoRequestProto\x1a..hadoop.yarn.GetQueueUserAclsInfoResponseProto\x12s\n\x12getDelegationToken\x12-.hadoop.common.GetDelegationTokenRequestProto\x1a..hadoop.common.GetDelegationTokenResponseProto\x12y\n\x14renewDelegationToken\x12/.hadoop.common.RenewDelegationTokenRequestProto\x1a\x30.hadoop.common.RenewDelegationTokenResponseProto\x12|\n\x15\x63\x61ncelDelegationToken\x12\x30.hadoop.common.CancelDelegationTokenRequestProto\x1a\x31.hadoop.common.CancelDelegationTokenResponseProtoB?\n\x1corg.apache.hadoop.yarn.protoB\x19\x41pplicationClientProtocol\x88\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\034org.apache.hadoop.yarn.protoB\031ApplicationClientProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
