/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_bkjournal_2eproto__INCLUDED
#define PROTOBUF_C_bkjournal_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "hdfs.pb-c.h"

typedef struct _Hadoop__Hdfs__VersionProto Hadoop__Hdfs__VersionProto;
typedef struct _Hadoop__Hdfs__EditLogLedgerProto Hadoop__Hdfs__EditLogLedgerProto;
typedef struct _Hadoop__Hdfs__MaxTxIdProto Hadoop__Hdfs__MaxTxIdProto;
typedef struct _Hadoop__Hdfs__CurrentInprogressProto Hadoop__Hdfs__CurrentInprogressProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Hdfs__VersionProto
{
  ProtobufCMessage base;
  int32_t layoutversion;
  Hadoop__Hdfs__NamespaceInfoProto *namespaceinfo;
};
#define HADOOP__HDFS__VERSION_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__version_proto__descriptor) \
    , 0, NULL }


struct  _Hadoop__Hdfs__EditLogLedgerProto
{
  ProtobufCMessage base;
  int32_t datalayoutversion;
  int64_t ledgerid;
  int64_t firsttxid;
  protobuf_c_boolean has_lasttxid;
  int64_t lasttxid;
};
#define HADOOP__HDFS__EDIT_LOG_LEDGER_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__edit_log_ledger_proto__descriptor) \
    , 0, 0, 0, 0,0 }


struct  _Hadoop__Hdfs__MaxTxIdProto
{
  ProtobufCMessage base;
  int64_t txid;
};
#define HADOOP__HDFS__MAX_TX_ID_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__max_tx_id_proto__descriptor) \
    , 0 }


struct  _Hadoop__Hdfs__CurrentInprogressProto
{
  ProtobufCMessage base;
  char *path;
  char *hostname;
};
#define HADOOP__HDFS__CURRENT_INPROGRESS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__current_inprogress_proto__descriptor) \
    , NULL, NULL }


/* Hadoop__Hdfs__VersionProto methods */
void   hadoop__hdfs__version_proto__init
                     (Hadoop__Hdfs__VersionProto         *message);
size_t hadoop__hdfs__version_proto__get_packed_size
                     (const Hadoop__Hdfs__VersionProto   *message);
size_t hadoop__hdfs__version_proto__pack
                     (const Hadoop__Hdfs__VersionProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__version_proto__pack_to_buffer
                     (const Hadoop__Hdfs__VersionProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__VersionProto *
       hadoop__hdfs__version_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__version_proto__free_unpacked
                     (Hadoop__Hdfs__VersionProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__EditLogLedgerProto methods */
void   hadoop__hdfs__edit_log_ledger_proto__init
                     (Hadoop__Hdfs__EditLogLedgerProto         *message);
size_t hadoop__hdfs__edit_log_ledger_proto__get_packed_size
                     (const Hadoop__Hdfs__EditLogLedgerProto   *message);
size_t hadoop__hdfs__edit_log_ledger_proto__pack
                     (const Hadoop__Hdfs__EditLogLedgerProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__edit_log_ledger_proto__pack_to_buffer
                     (const Hadoop__Hdfs__EditLogLedgerProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__EditLogLedgerProto *
       hadoop__hdfs__edit_log_ledger_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__edit_log_ledger_proto__free_unpacked
                     (Hadoop__Hdfs__EditLogLedgerProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__MaxTxIdProto methods */
void   hadoop__hdfs__max_tx_id_proto__init
                     (Hadoop__Hdfs__MaxTxIdProto         *message);
size_t hadoop__hdfs__max_tx_id_proto__get_packed_size
                     (const Hadoop__Hdfs__MaxTxIdProto   *message);
size_t hadoop__hdfs__max_tx_id_proto__pack
                     (const Hadoop__Hdfs__MaxTxIdProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__max_tx_id_proto__pack_to_buffer
                     (const Hadoop__Hdfs__MaxTxIdProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__MaxTxIdProto *
       hadoop__hdfs__max_tx_id_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__max_tx_id_proto__free_unpacked
                     (Hadoop__Hdfs__MaxTxIdProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__CurrentInprogressProto methods */
void   hadoop__hdfs__current_inprogress_proto__init
                     (Hadoop__Hdfs__CurrentInprogressProto         *message);
size_t hadoop__hdfs__current_inprogress_proto__get_packed_size
                     (const Hadoop__Hdfs__CurrentInprogressProto   *message);
size_t hadoop__hdfs__current_inprogress_proto__pack
                     (const Hadoop__Hdfs__CurrentInprogressProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__current_inprogress_proto__pack_to_buffer
                     (const Hadoop__Hdfs__CurrentInprogressProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__CurrentInprogressProto *
       hadoop__hdfs__current_inprogress_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__current_inprogress_proto__free_unpacked
                     (Hadoop__Hdfs__CurrentInprogressProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Hdfs__VersionProto_Closure)
                 (const Hadoop__Hdfs__VersionProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__EditLogLedgerProto_Closure)
                 (const Hadoop__Hdfs__EditLogLedgerProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__MaxTxIdProto_Closure)
                 (const Hadoop__Hdfs__MaxTxIdProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__CurrentInprogressProto_Closure)
                 (const Hadoop__Hdfs__CurrentInprogressProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__hdfs__version_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__edit_log_ledger_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__max_tx_id_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__current_inprogress_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_bkjournal_2eproto__INCLUDED */
