/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_containermanagement_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_C_containermanagement_5fprotocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_service_protos.pb-c.h"



/* --- enums --- */


/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */

typedef struct _Hadoop__Yarn__ContainerManagementProtocolService_Service Hadoop__Yarn__ContainerManagementProtocolService_Service;
struct _Hadoop__Yarn__ContainerManagementProtocolService_Service
{
  ProtobufCService base;
  void (*start_containers)(Hadoop__Yarn__ContainerManagementProtocolService_Service *service,
                           const Hadoop__Yarn__StartContainersRequestProto *input,
                           Hadoop__Yarn__StartContainersResponseProto_Closure closure,
                           void *closure_data);
  void (*stop_containers)(Hadoop__Yarn__ContainerManagementProtocolService_Service *service,
                          const Hadoop__Yarn__StopContainersRequestProto *input,
                          Hadoop__Yarn__StopContainersResponseProto_Closure closure,
                          void *closure_data);
  void (*get_container_statuses)(Hadoop__Yarn__ContainerManagementProtocolService_Service *service,
                                 const Hadoop__Yarn__GetContainerStatusesRequestProto *input,
                                 Hadoop__Yarn__GetContainerStatusesResponseProto_Closure closure,
                                 void *closure_data);
};
typedef void (*Hadoop__Yarn__ContainerManagementProtocolService_ServiceDestroy)(Hadoop__Yarn__ContainerManagementProtocolService_Service *);
void hadoop__yarn__container_management_protocol_service__init (Hadoop__Yarn__ContainerManagementProtocolService_Service *service,
                                                                Hadoop__Yarn__ContainerManagementProtocolService_ServiceDestroy destroy);
#define HADOOP__YARN__CONTAINER_MANAGEMENT_PROTOCOL_SERVICE__BASE_INIT \
    { &hadoop__yarn__container_management_protocol_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__YARN__CONTAINER_MANAGEMENT_PROTOCOL_SERVICE__INIT(function_prefix__) \
    { HADOOP__YARN__CONTAINER_MANAGEMENT_PROTOCOL_SERVICE__BASE_INIT,\
      function_prefix__ ## start_containers,\
      function_prefix__ ## stop_containers,\
      function_prefix__ ## get_container_statuses  }
void hadoop__yarn__container_management_protocol_service__start_containers(ProtobufCService *service,
                                                                           const Hadoop__Yarn__StartContainersRequestProto *input,
                                                                           Hadoop__Yarn__StartContainersResponseProto_Closure closure,
                                                                           void *closure_data);
void hadoop__yarn__container_management_protocol_service__stop_containers(ProtobufCService *service,
                                                                          const Hadoop__Yarn__StopContainersRequestProto *input,
                                                                          Hadoop__Yarn__StopContainersResponseProto_Closure closure,
                                                                          void *closure_data);
void hadoop__yarn__container_management_protocol_service__get_container_statuses(ProtobufCService *service,
                                                                                 const Hadoop__Yarn__GetContainerStatusesRequestProto *input,
                                                                                 Hadoop__Yarn__GetContainerStatusesResponseProto_Closure closure,
                                                                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCServiceDescriptor hadoop__yarn__container_management_protocol_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_containermanagement_5fprotocol_2eproto__INCLUDED */
