/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_GetUserMappingsProtocol_2eproto__INCLUDED
#define PROTOBUF_C_GetUserMappingsProtocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Hadoop__Common__GetGroupsForUserRequestProto Hadoop__Common__GetGroupsForUserRequestProto;
typedef struct _Hadoop__Common__GetGroupsForUserResponseProto Hadoop__Common__GetGroupsForUserResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Common__GetGroupsForUserRequestProto
{
  ProtobufCMessage base;
  char *user;
};
#define HADOOP__COMMON__GET_GROUPS_FOR_USER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__get_groups_for_user_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Common__GetGroupsForUserResponseProto
{
  ProtobufCMessage base;
  size_t n_groups;
  char **groups;
};
#define HADOOP__COMMON__GET_GROUPS_FOR_USER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__get_groups_for_user_response_proto__descriptor) \
    , 0,NULL }


/* Hadoop__Common__GetGroupsForUserRequestProto methods */
void   hadoop__common__get_groups_for_user_request_proto__init
                     (Hadoop__Common__GetGroupsForUserRequestProto         *message);
size_t hadoop__common__get_groups_for_user_request_proto__get_packed_size
                     (const Hadoop__Common__GetGroupsForUserRequestProto   *message);
size_t hadoop__common__get_groups_for_user_request_proto__pack
                     (const Hadoop__Common__GetGroupsForUserRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__get_groups_for_user_request_proto__pack_to_buffer
                     (const Hadoop__Common__GetGroupsForUserRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__GetGroupsForUserRequestProto *
       hadoop__common__get_groups_for_user_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__get_groups_for_user_request_proto__free_unpacked
                     (Hadoop__Common__GetGroupsForUserRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__GetGroupsForUserResponseProto methods */
void   hadoop__common__get_groups_for_user_response_proto__init
                     (Hadoop__Common__GetGroupsForUserResponseProto         *message);
size_t hadoop__common__get_groups_for_user_response_proto__get_packed_size
                     (const Hadoop__Common__GetGroupsForUserResponseProto   *message);
size_t hadoop__common__get_groups_for_user_response_proto__pack
                     (const Hadoop__Common__GetGroupsForUserResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__get_groups_for_user_response_proto__pack_to_buffer
                     (const Hadoop__Common__GetGroupsForUserResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__GetGroupsForUserResponseProto *
       hadoop__common__get_groups_for_user_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__get_groups_for_user_response_proto__free_unpacked
                     (Hadoop__Common__GetGroupsForUserResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Common__GetGroupsForUserRequestProto_Closure)
                 (const Hadoop__Common__GetGroupsForUserRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__GetGroupsForUserResponseProto_Closure)
                 (const Hadoop__Common__GetGroupsForUserResponseProto *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Hadoop__Common__GetUserMappingsProtocolService_Service Hadoop__Common__GetUserMappingsProtocolService_Service;
struct _Hadoop__Common__GetUserMappingsProtocolService_Service
{
  ProtobufCService base;
  void (*get_groups_for_user)(Hadoop__Common__GetUserMappingsProtocolService_Service *service,
                              const Hadoop__Common__GetGroupsForUserRequestProto *input,
                              Hadoop__Common__GetGroupsForUserResponseProto_Closure closure,
                              void *closure_data);
};
typedef void (*Hadoop__Common__GetUserMappingsProtocolService_ServiceDestroy)(Hadoop__Common__GetUserMappingsProtocolService_Service *);
void hadoop__common__get_user_mappings_protocol_service__init (Hadoop__Common__GetUserMappingsProtocolService_Service *service,
                                                               Hadoop__Common__GetUserMappingsProtocolService_ServiceDestroy destroy);
#define HADOOP__COMMON__GET_USER_MAPPINGS_PROTOCOL_SERVICE__BASE_INIT \
    { &hadoop__common__get_user_mappings_protocol_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__COMMON__GET_USER_MAPPINGS_PROTOCOL_SERVICE__INIT(function_prefix__) \
    { HADOOP__COMMON__GET_USER_MAPPINGS_PROTOCOL_SERVICE__BASE_INIT,\
      function_prefix__ ## get_groups_for_user  }
void hadoop__common__get_user_mappings_protocol_service__get_groups_for_user(ProtobufCService *service,
                                                                             const Hadoop__Common__GetGroupsForUserRequestProto *input,
                                                                             Hadoop__Common__GetGroupsForUserResponseProto_Closure closure,
                                                                             void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__common__get_groups_for_user_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__get_groups_for_user_response_proto__descriptor;
extern const ProtobufCServiceDescriptor hadoop__common__get_user_mappings_protocol_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_GetUserMappingsProtocol_2eproto__INCLUDED */
