/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_InterDatanodeProtocol_2eproto__INCLUDED
#define PROTOBUF_C_InterDatanodeProtocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "hdfs.pb-c.h"

typedef struct _Hadoop__Hdfs__InitReplicaRecoveryRequestProto Hadoop__Hdfs__InitReplicaRecoveryRequestProto;
typedef struct _Hadoop__Hdfs__InitReplicaRecoveryResponseProto Hadoop__Hdfs__InitReplicaRecoveryResponseProto;
typedef struct _Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto;
typedef struct _Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Hdfs__InitReplicaRecoveryRequestProto
{
  ProtobufCMessage base;
  Hadoop__Hdfs__RecoveringBlockProto *block;
};
#define HADOOP__HDFS__INIT_REPLICA_RECOVERY_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__init_replica_recovery_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Hdfs__InitReplicaRecoveryResponseProto
{
  ProtobufCMessage base;
  protobuf_c_boolean replicafound;
  protobuf_c_boolean has_state;
  Hadoop__Hdfs__ReplicaStateProto state;
  Hadoop__Hdfs__BlockProto *block;
};
#define HADOOP__HDFS__INIT_REPLICA_RECOVERY_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__init_replica_recovery_response_proto__descriptor) \
    , 0, 0,0, NULL }


struct  _Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto
{
  ProtobufCMessage base;
  Hadoop__Hdfs__ExtendedBlockProto *block;
  uint64_t recoveryid;
  uint64_t newlength;
};
#define HADOOP__HDFS__UPDATE_REPLICA_UNDER_RECOVERY_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor) \
    , NULL, 0, 0 }


struct  _Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto
{
  ProtobufCMessage base;
  char *storageid;
};
#define HADOOP__HDFS__UPDATE_REPLICA_UNDER_RECOVERY_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor) \
    , NULL }


/* Hadoop__Hdfs__InitReplicaRecoveryRequestProto methods */
void   hadoop__hdfs__init_replica_recovery_request_proto__init
                     (Hadoop__Hdfs__InitReplicaRecoveryRequestProto         *message);
size_t hadoop__hdfs__init_replica_recovery_request_proto__get_packed_size
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto   *message);
size_t hadoop__hdfs__init_replica_recovery_request_proto__pack
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__init_replica_recovery_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__InitReplicaRecoveryRequestProto *
       hadoop__hdfs__init_replica_recovery_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__init_replica_recovery_request_proto__free_unpacked
                     (Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__InitReplicaRecoveryResponseProto methods */
void   hadoop__hdfs__init_replica_recovery_response_proto__init
                     (Hadoop__Hdfs__InitReplicaRecoveryResponseProto         *message);
size_t hadoop__hdfs__init_replica_recovery_response_proto__get_packed_size
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto   *message);
size_t hadoop__hdfs__init_replica_recovery_response_proto__pack
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__init_replica_recovery_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__InitReplicaRecoveryResponseProto *
       hadoop__hdfs__init_replica_recovery_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__init_replica_recovery_response_proto__free_unpacked
                     (Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto methods */
void   hadoop__hdfs__update_replica_under_recovery_request_proto__init
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto         *message);
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__get_packed_size
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto   *message);
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__pack
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__update_replica_under_recovery_request_proto__pack_to_buffer
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *
       hadoop__hdfs__update_replica_under_recovery_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__update_replica_under_recovery_request_proto__free_unpacked
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto methods */
void   hadoop__hdfs__update_replica_under_recovery_response_proto__init
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto         *message);
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__get_packed_size
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto   *message);
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__pack
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__hdfs__update_replica_under_recovery_response_proto__pack_to_buffer
                     (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *
       hadoop__hdfs__update_replica_under_recovery_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__hdfs__update_replica_under_recovery_response_proto__free_unpacked
                     (Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Hdfs__InitReplicaRecoveryRequestProto_Closure)
                 (const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__InitReplicaRecoveryResponseProto_Closure)
                 (const Hadoop__Hdfs__InitReplicaRecoveryResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto_Closure)
                 (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto_Closure)
                 (const Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Hadoop__Hdfs__InterDatanodeProtocolService_Service Hadoop__Hdfs__InterDatanodeProtocolService_Service;
struct _Hadoop__Hdfs__InterDatanodeProtocolService_Service
{
  ProtobufCService base;
  void (*init_replica_recovery)(Hadoop__Hdfs__InterDatanodeProtocolService_Service *service,
                                const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *input,
                                Hadoop__Hdfs__InitReplicaRecoveryResponseProto_Closure closure,
                                void *closure_data);
  void (*update_replica_under_recovery)(Hadoop__Hdfs__InterDatanodeProtocolService_Service *service,
                                        const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *input,
                                        Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto_Closure closure,
                                        void *closure_data);
};
typedef void (*Hadoop__Hdfs__InterDatanodeProtocolService_ServiceDestroy)(Hadoop__Hdfs__InterDatanodeProtocolService_Service *);
void hadoop__hdfs__inter_datanode_protocol_service__init (Hadoop__Hdfs__InterDatanodeProtocolService_Service *service,
                                                          Hadoop__Hdfs__InterDatanodeProtocolService_ServiceDestroy destroy);
#define HADOOP__HDFS__INTER_DATANODE_PROTOCOL_SERVICE__BASE_INIT \
    { &hadoop__hdfs__inter_datanode_protocol_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__HDFS__INTER_DATANODE_PROTOCOL_SERVICE__INIT(function_prefix__) \
    { HADOOP__HDFS__INTER_DATANODE_PROTOCOL_SERVICE__BASE_INIT,\
      function_prefix__ ## init_replica_recovery,\
      function_prefix__ ## update_replica_under_recovery  }
void hadoop__hdfs__inter_datanode_protocol_service__init_replica_recovery(ProtobufCService *service,
                                                                          const Hadoop__Hdfs__InitReplicaRecoveryRequestProto *input,
                                                                          Hadoop__Hdfs__InitReplicaRecoveryResponseProto_Closure closure,
                                                                          void *closure_data);
void hadoop__hdfs__inter_datanode_protocol_service__update_replica_under_recovery(ProtobufCService *service,
                                                                                  const Hadoop__Hdfs__UpdateReplicaUnderRecoveryRequestProto *input,
                                                                                  Hadoop__Hdfs__UpdateReplicaUnderRecoveryResponseProto_Closure closure,
                                                                                  void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__hdfs__init_replica_recovery_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__init_replica_recovery_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__update_replica_under_recovery_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__hdfs__update_replica_under_recovery_response_proto__descriptor;
extern const ProtobufCServiceDescriptor hadoop__hdfs__inter_datanode_protocol_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_InterDatanodeProtocol_2eproto__INCLUDED */
