/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_IpcConnectionContext_2eproto__INCLUDED
#define PROTOBUF_C_IpcConnectionContext_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Hadoop__Common__UserInformationProto Hadoop__Common__UserInformationProto;
typedef struct _Hadoop__Common__IpcConnectionContextProto Hadoop__Common__IpcConnectionContextProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Common__UserInformationProto
{
  ProtobufCMessage base;
  char *effectiveuser;
  char *realuser;
};
#define HADOOP__COMMON__USER_INFORMATION_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__user_information_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Common__IpcConnectionContextProto
{
  ProtobufCMessage base;
  Hadoop__Common__UserInformationProto *userinfo;
  char *protocol;
};
#define HADOOP__COMMON__IPC_CONNECTION_CONTEXT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__ipc_connection_context_proto__descriptor) \
    , NULL, NULL }


/* Hadoop__Common__UserInformationProto methods */
void   hadoop__common__user_information_proto__init
                     (Hadoop__Common__UserInformationProto         *message);
size_t hadoop__common__user_information_proto__get_packed_size
                     (const Hadoop__Common__UserInformationProto   *message);
size_t hadoop__common__user_information_proto__pack
                     (const Hadoop__Common__UserInformationProto   *message,
                      uint8_t             *out);
size_t hadoop__common__user_information_proto__pack_to_buffer
                     (const Hadoop__Common__UserInformationProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__UserInformationProto *
       hadoop__common__user_information_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__user_information_proto__free_unpacked
                     (Hadoop__Common__UserInformationProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__IpcConnectionContextProto methods */
void   hadoop__common__ipc_connection_context_proto__init
                     (Hadoop__Common__IpcConnectionContextProto         *message);
size_t hadoop__common__ipc_connection_context_proto__get_packed_size
                     (const Hadoop__Common__IpcConnectionContextProto   *message);
size_t hadoop__common__ipc_connection_context_proto__pack
                     (const Hadoop__Common__IpcConnectionContextProto   *message,
                      uint8_t             *out);
size_t hadoop__common__ipc_connection_context_proto__pack_to_buffer
                     (const Hadoop__Common__IpcConnectionContextProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__IpcConnectionContextProto *
       hadoop__common__ipc_connection_context_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__ipc_connection_context_proto__free_unpacked
                     (Hadoop__Common__IpcConnectionContextProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Common__UserInformationProto_Closure)
                 (const Hadoop__Common__UserInformationProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__IpcConnectionContextProto_Closure)
                 (const Hadoop__Common__IpcConnectionContextProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__common__user_information_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__ipc_connection_context_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_IpcConnectionContext_2eproto__INCLUDED */
