/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_RefreshAuthorizationPolicyProtocol_2eproto__INCLUDED
#define PROTOBUF_C_RefreshAuthorizationPolicyProtocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Hadoop__Common__RefreshServiceAclRequestProto Hadoop__Common__RefreshServiceAclRequestProto;
typedef struct _Hadoop__Common__RefreshServiceAclResponseProto Hadoop__Common__RefreshServiceAclResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Common__RefreshServiceAclRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_SERVICE_ACL_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_service_acl_request_proto__descriptor) \
     }


struct  _Hadoop__Common__RefreshServiceAclResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_SERVICE_ACL_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_service_acl_response_proto__descriptor) \
     }


/* Hadoop__Common__RefreshServiceAclRequestProto methods */
void   hadoop__common__refresh_service_acl_request_proto__init
                     (Hadoop__Common__RefreshServiceAclRequestProto         *message);
size_t hadoop__common__refresh_service_acl_request_proto__get_packed_size
                     (const Hadoop__Common__RefreshServiceAclRequestProto   *message);
size_t hadoop__common__refresh_service_acl_request_proto__pack
                     (const Hadoop__Common__RefreshServiceAclRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_service_acl_request_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshServiceAclRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshServiceAclRequestProto *
       hadoop__common__refresh_service_acl_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_service_acl_request_proto__free_unpacked
                     (Hadoop__Common__RefreshServiceAclRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__RefreshServiceAclResponseProto methods */
void   hadoop__common__refresh_service_acl_response_proto__init
                     (Hadoop__Common__RefreshServiceAclResponseProto         *message);
size_t hadoop__common__refresh_service_acl_response_proto__get_packed_size
                     (const Hadoop__Common__RefreshServiceAclResponseProto   *message);
size_t hadoop__common__refresh_service_acl_response_proto__pack
                     (const Hadoop__Common__RefreshServiceAclResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_service_acl_response_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshServiceAclResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshServiceAclResponseProto *
       hadoop__common__refresh_service_acl_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_service_acl_response_proto__free_unpacked
                     (Hadoop__Common__RefreshServiceAclResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Common__RefreshServiceAclRequestProto_Closure)
                 (const Hadoop__Common__RefreshServiceAclRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__RefreshServiceAclResponseProto_Closure)
                 (const Hadoop__Common__RefreshServiceAclResponseProto *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service;
struct _Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service
{
  ProtobufCService base;
  void (*refresh_service_acl)(Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service *service,
                              const Hadoop__Common__RefreshServiceAclRequestProto *input,
                              Hadoop__Common__RefreshServiceAclResponseProto_Closure closure,
                              void *closure_data);
};
typedef void (*Hadoop__Common__RefreshAuthorizationPolicyProtocolService_ServiceDestroy)(Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service *);
void hadoop__common__refresh_authorization_policy_protocol_service__init (Hadoop__Common__RefreshAuthorizationPolicyProtocolService_Service *service,
                                                                          Hadoop__Common__RefreshAuthorizationPolicyProtocolService_ServiceDestroy destroy);
#define HADOOP__COMMON__REFRESH_AUTHORIZATION_POLICY_PROTOCOL_SERVICE__BASE_INIT \
    { &hadoop__common__refresh_authorization_policy_protocol_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__COMMON__REFRESH_AUTHORIZATION_POLICY_PROTOCOL_SERVICE__INIT(function_prefix__) \
    { HADOOP__COMMON__REFRESH_AUTHORIZATION_POLICY_PROTOCOL_SERVICE__BASE_INIT,\
      function_prefix__ ## refresh_service_acl  }
void hadoop__common__refresh_authorization_policy_protocol_service__refresh_service_acl(ProtobufCService *service,
                                                                                        const Hadoop__Common__RefreshServiceAclRequestProto *input,
                                                                                        Hadoop__Common__RefreshServiceAclResponseProto_Closure closure,
                                                                                        void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__common__refresh_service_acl_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__refresh_service_acl_response_proto__descriptor;
extern const ProtobufCServiceDescriptor hadoop__common__refresh_authorization_policy_protocol_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_RefreshAuthorizationPolicyProtocol_2eproto__INCLUDED */
