/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_RefreshUserMappingsProtocol_2eproto__INCLUDED
#define PROTOBUF_C_RefreshUserMappingsProtocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Hadoop__Common__RefreshUserToGroupsMappingsRequestProto Hadoop__Common__RefreshUserToGroupsMappingsRequestProto;
typedef struct _Hadoop__Common__RefreshUserToGroupsMappingsResponseProto Hadoop__Common__RefreshUserToGroupsMappingsResponseProto;
typedef struct _Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto;
typedef struct _Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Common__RefreshUserToGroupsMappingsRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_USER_TO_GROUPS_MAPPINGS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_user_to_groups_mappings_request_proto__descriptor) \
     }


struct  _Hadoop__Common__RefreshUserToGroupsMappingsResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_USER_TO_GROUPS_MAPPINGS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_user_to_groups_mappings_response_proto__descriptor) \
     }


struct  _Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_super_user_groups_configuration_request_proto__descriptor) \
     }


struct  _Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__COMMON__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__common__refresh_super_user_groups_configuration_response_proto__descriptor) \
     }


/* Hadoop__Common__RefreshUserToGroupsMappingsRequestProto methods */
void   hadoop__common__refresh_user_to_groups_mappings_request_proto__init
                     (Hadoop__Common__RefreshUserToGroupsMappingsRequestProto         *message);
size_t hadoop__common__refresh_user_to_groups_mappings_request_proto__get_packed_size
                     (const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto   *message);
size_t hadoop__common__refresh_user_to_groups_mappings_request_proto__pack
                     (const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_user_to_groups_mappings_request_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshUserToGroupsMappingsRequestProto *
       hadoop__common__refresh_user_to_groups_mappings_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_user_to_groups_mappings_request_proto__free_unpacked
                     (Hadoop__Common__RefreshUserToGroupsMappingsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__RefreshUserToGroupsMappingsResponseProto methods */
void   hadoop__common__refresh_user_to_groups_mappings_response_proto__init
                     (Hadoop__Common__RefreshUserToGroupsMappingsResponseProto         *message);
size_t hadoop__common__refresh_user_to_groups_mappings_response_proto__get_packed_size
                     (const Hadoop__Common__RefreshUserToGroupsMappingsResponseProto   *message);
size_t hadoop__common__refresh_user_to_groups_mappings_response_proto__pack
                     (const Hadoop__Common__RefreshUserToGroupsMappingsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_user_to_groups_mappings_response_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshUserToGroupsMappingsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshUserToGroupsMappingsResponseProto *
       hadoop__common__refresh_user_to_groups_mappings_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_user_to_groups_mappings_response_proto__free_unpacked
                     (Hadoop__Common__RefreshUserToGroupsMappingsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto methods */
void   hadoop__common__refresh_super_user_groups_configuration_request_proto__init
                     (Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto         *message);
size_t hadoop__common__refresh_super_user_groups_configuration_request_proto__get_packed_size
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto   *message);
size_t hadoop__common__refresh_super_user_groups_configuration_request_proto__pack
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_super_user_groups_configuration_request_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto *
       hadoop__common__refresh_super_user_groups_configuration_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_super_user_groups_configuration_request_proto__free_unpacked
                     (Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto methods */
void   hadoop__common__refresh_super_user_groups_configuration_response_proto__init
                     (Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto         *message);
size_t hadoop__common__refresh_super_user_groups_configuration_response_proto__get_packed_size
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto   *message);
size_t hadoop__common__refresh_super_user_groups_configuration_response_proto__pack
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__common__refresh_super_user_groups_configuration_response_proto__pack_to_buffer
                     (const Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto *
       hadoop__common__refresh_super_user_groups_configuration_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__common__refresh_super_user_groups_configuration_response_proto__free_unpacked
                     (Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Common__RefreshUserToGroupsMappingsRequestProto_Closure)
                 (const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__RefreshUserToGroupsMappingsResponseProto_Closure)
                 (const Hadoop__Common__RefreshUserToGroupsMappingsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto_Closure)
                 (const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto_Closure)
                 (const Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Hadoop__Common__RefreshUserMappingsProtocolService_Service Hadoop__Common__RefreshUserMappingsProtocolService_Service;
struct _Hadoop__Common__RefreshUserMappingsProtocolService_Service
{
  ProtobufCService base;
  void (*refresh_user_to_groups_mappings)(Hadoop__Common__RefreshUserMappingsProtocolService_Service *service,
                                          const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto *input,
                                          Hadoop__Common__RefreshUserToGroupsMappingsResponseProto_Closure closure,
                                          void *closure_data);
  void (*refresh_super_user_groups_configuration)(Hadoop__Common__RefreshUserMappingsProtocolService_Service *service,
                                                  const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto *input,
                                                  Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto_Closure closure,
                                                  void *closure_data);
};
typedef void (*Hadoop__Common__RefreshUserMappingsProtocolService_ServiceDestroy)(Hadoop__Common__RefreshUserMappingsProtocolService_Service *);
void hadoop__common__refresh_user_mappings_protocol_service__init (Hadoop__Common__RefreshUserMappingsProtocolService_Service *service,
                                                                   Hadoop__Common__RefreshUserMappingsProtocolService_ServiceDestroy destroy);
#define HADOOP__COMMON__REFRESH_USER_MAPPINGS_PROTOCOL_SERVICE__BASE_INIT \
    { &hadoop__common__refresh_user_mappings_protocol_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__COMMON__REFRESH_USER_MAPPINGS_PROTOCOL_SERVICE__INIT(function_prefix__) \
    { HADOOP__COMMON__REFRESH_USER_MAPPINGS_PROTOCOL_SERVICE__BASE_INIT,\
      function_prefix__ ## refresh_user_to_groups_mappings,\
      function_prefix__ ## refresh_super_user_groups_configuration  }
void hadoop__common__refresh_user_mappings_protocol_service__refresh_user_to_groups_mappings(ProtobufCService *service,
                                                                                             const Hadoop__Common__RefreshUserToGroupsMappingsRequestProto *input,
                                                                                             Hadoop__Common__RefreshUserToGroupsMappingsResponseProto_Closure closure,
                                                                                             void *closure_data);
void hadoop__common__refresh_user_mappings_protocol_service__refresh_super_user_groups_configuration(ProtobufCService *service,
                                                                                                     const Hadoop__Common__RefreshSuperUserGroupsConfigurationRequestProto *input,
                                                                                                     Hadoop__Common__RefreshSuperUserGroupsConfigurationResponseProto_Closure closure,
                                                                                                     void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__common__refresh_user_to_groups_mappings_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__refresh_user_to_groups_mappings_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__refresh_super_user_groups_configuration_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__common__refresh_super_user_groups_configuration_response_proto__descriptor;
extern const ProtobufCServiceDescriptor hadoop__common__refresh_user_mappings_protocol_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_RefreshUserMappingsProtocol_2eproto__INCLUDED */
