/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ResourceTracker_2eproto__INCLUDED
#define PROTOBUF_C_ResourceTracker_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_server_common_service_protos.pb-c.h"



/* --- enums --- */


/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */

typedef struct _Hadoop__Yarn__ResourceTrackerService_Service Hadoop__Yarn__ResourceTrackerService_Service;
struct _Hadoop__Yarn__ResourceTrackerService_Service
{
  ProtobufCService base;
  void (*register_node_manager)(Hadoop__Yarn__ResourceTrackerService_Service *service,
                                const Hadoop__Yarn__RegisterNodeManagerRequestProto *input,
                                Hadoop__Yarn__RegisterNodeManagerResponseProto_Closure closure,
                                void *closure_data);
  void (*node_heartbeat)(Hadoop__Yarn__ResourceTrackerService_Service *service,
                         const Hadoop__Yarn__NodeHeartbeatRequestProto *input,
                         Hadoop__Yarn__NodeHeartbeatResponseProto_Closure closure,
                         void *closure_data);
};
typedef void (*Hadoop__Yarn__ResourceTrackerService_ServiceDestroy)(Hadoop__Yarn__ResourceTrackerService_Service *);
void hadoop__yarn__resource_tracker_service__init (Hadoop__Yarn__ResourceTrackerService_Service *service,
                                                   Hadoop__Yarn__ResourceTrackerService_ServiceDestroy destroy);
#define HADOOP__YARN__RESOURCE_TRACKER_SERVICE__BASE_INIT \
    { &hadoop__yarn__resource_tracker_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define HADOOP__YARN__RESOURCE_TRACKER_SERVICE__INIT(function_prefix__) \
    { HADOOP__YARN__RESOURCE_TRACKER_SERVICE__BASE_INIT,\
      function_prefix__ ## register_node_manager,\
      function_prefix__ ## node_heartbeat  }
void hadoop__yarn__resource_tracker_service__register_node_manager(ProtobufCService *service,
                                                                   const Hadoop__Yarn__RegisterNodeManagerRequestProto *input,
                                                                   Hadoop__Yarn__RegisterNodeManagerResponseProto_Closure closure,
                                                                   void *closure_data);
void hadoop__yarn__resource_tracker_service__node_heartbeat(ProtobufCService *service,
                                                            const Hadoop__Yarn__NodeHeartbeatRequestProto *input,
                                                            Hadoop__Yarn__NodeHeartbeatResponseProto_Closure closure,
                                                            void *closure_data);

/* --- descriptors --- */

extern const ProtobufCServiceDescriptor hadoop__yarn__resource_tracker_service__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ResourceTracker_2eproto__INCLUDED */
