/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "Security.pb-c.h"

typedef struct _Hadoop__Yarn__SerializedExceptionProto Hadoop__Yarn__SerializedExceptionProto;
typedef struct _Hadoop__Yarn__ApplicationIdProto Hadoop__Yarn__ApplicationIdProto;
typedef struct _Hadoop__Yarn__ApplicationAttemptIdProto Hadoop__Yarn__ApplicationAttemptIdProto;
typedef struct _Hadoop__Yarn__ContainerIdProto Hadoop__Yarn__ContainerIdProto;
typedef struct _Hadoop__Yarn__ResourceProto Hadoop__Yarn__ResourceProto;
typedef struct _Hadoop__Yarn__PriorityProto Hadoop__Yarn__PriorityProto;
typedef struct _Hadoop__Yarn__ContainerProto Hadoop__Yarn__ContainerProto;
typedef struct _Hadoop__Yarn__URLProto Hadoop__Yarn__URLProto;
typedef struct _Hadoop__Yarn__LocalResourceProto Hadoop__Yarn__LocalResourceProto;
typedef struct _Hadoop__Yarn__ApplicationResourceUsageReportProto Hadoop__Yarn__ApplicationResourceUsageReportProto;
typedef struct _Hadoop__Yarn__ApplicationReportProto Hadoop__Yarn__ApplicationReportProto;
typedef struct _Hadoop__Yarn__NodeIdProto Hadoop__Yarn__NodeIdProto;
typedef struct _Hadoop__Yarn__NodeReportProto Hadoop__Yarn__NodeReportProto;
typedef struct _Hadoop__Yarn__ResourceRequestProto Hadoop__Yarn__ResourceRequestProto;
typedef struct _Hadoop__Yarn__PreemptionMessageProto Hadoop__Yarn__PreemptionMessageProto;
typedef struct _Hadoop__Yarn__StrictPreemptionContractProto Hadoop__Yarn__StrictPreemptionContractProto;
typedef struct _Hadoop__Yarn__PreemptionContractProto Hadoop__Yarn__PreemptionContractProto;
typedef struct _Hadoop__Yarn__PreemptionContainerProto Hadoop__Yarn__PreemptionContainerProto;
typedef struct _Hadoop__Yarn__PreemptionResourceRequestProto Hadoop__Yarn__PreemptionResourceRequestProto;
typedef struct _Hadoop__Yarn__ResourceBlacklistRequestProto Hadoop__Yarn__ResourceBlacklistRequestProto;
typedef struct _Hadoop__Yarn__ApplicationSubmissionContextProto Hadoop__Yarn__ApplicationSubmissionContextProto;
typedef struct _Hadoop__Yarn__ApplicationACLMapProto Hadoop__Yarn__ApplicationACLMapProto;
typedef struct _Hadoop__Yarn__YarnClusterMetricsProto Hadoop__Yarn__YarnClusterMetricsProto;
typedef struct _Hadoop__Yarn__QueueInfoProto Hadoop__Yarn__QueueInfoProto;
typedef struct _Hadoop__Yarn__QueueUserACLInfoProto Hadoop__Yarn__QueueUserACLInfoProto;
typedef struct _Hadoop__Yarn__ContainerLaunchContextProto Hadoop__Yarn__ContainerLaunchContextProto;
typedef struct _Hadoop__Yarn__ContainerStatusProto Hadoop__Yarn__ContainerStatusProto;
typedef struct _Hadoop__Yarn__StringLocalResourceMapProto Hadoop__Yarn__StringLocalResourceMapProto;
typedef struct _Hadoop__Yarn__StringStringMapProto Hadoop__Yarn__StringStringMapProto;
typedef struct _Hadoop__Yarn__StringBytesMapProto Hadoop__Yarn__StringBytesMapProto;


/* --- enums --- */

typedef enum _Hadoop__Yarn__ContainerStateProto {
  HADOOP__YARN__CONTAINER_STATE_PROTO__C_NEW = 1,
  HADOOP__YARN__CONTAINER_STATE_PROTO__C_RUNNING = 2,
  HADOOP__YARN__CONTAINER_STATE_PROTO__C_COMPLETE = 3
} Hadoop__Yarn__ContainerStateProto;
typedef enum _Hadoop__Yarn__YarnApplicationStateProto {
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__NEW = 1,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__NEW_SAVING = 2,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__SUBMITTED = 3,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__ACCEPTED = 4,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__RUNNING = 5,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__FINISHED = 6,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__FAILED = 7,
  HADOOP__YARN__YARN_APPLICATION_STATE_PROTO__KILLED = 8
} Hadoop__Yarn__YarnApplicationStateProto;
typedef enum _Hadoop__Yarn__FinalApplicationStatusProto {
  HADOOP__YARN__FINAL_APPLICATION_STATUS_PROTO__APP_UNDEFINED = 0,
  HADOOP__YARN__FINAL_APPLICATION_STATUS_PROTO__APP_SUCCEEDED = 1,
  HADOOP__YARN__FINAL_APPLICATION_STATUS_PROTO__APP_FAILED = 2,
  HADOOP__YARN__FINAL_APPLICATION_STATUS_PROTO__APP_KILLED = 3
} Hadoop__Yarn__FinalApplicationStatusProto;
typedef enum _Hadoop__Yarn__LocalResourceVisibilityProto {
  HADOOP__YARN__LOCAL_RESOURCE_VISIBILITY_PROTO__PUBLIC = 1,
  HADOOP__YARN__LOCAL_RESOURCE_VISIBILITY_PROTO__PRIVATE = 2,
  HADOOP__YARN__LOCAL_RESOURCE_VISIBILITY_PROTO__APPLICATION = 3
} Hadoop__Yarn__LocalResourceVisibilityProto;
typedef enum _Hadoop__Yarn__LocalResourceTypeProto {
  HADOOP__YARN__LOCAL_RESOURCE_TYPE_PROTO__ARCHIVE = 1,
  HADOOP__YARN__LOCAL_RESOURCE_TYPE_PROTO__FILE = 2,
  HADOOP__YARN__LOCAL_RESOURCE_TYPE_PROTO__PATTERN = 3
} Hadoop__Yarn__LocalResourceTypeProto;
typedef enum _Hadoop__Yarn__NodeStateProto {
  HADOOP__YARN__NODE_STATE_PROTO__NS_NEW = 1,
  HADOOP__YARN__NODE_STATE_PROTO__NS_RUNNING = 2,
  HADOOP__YARN__NODE_STATE_PROTO__NS_UNHEALTHY = 3,
  HADOOP__YARN__NODE_STATE_PROTO__NS_DECOMMISSIONED = 4,
  HADOOP__YARN__NODE_STATE_PROTO__NS_LOST = 5,
  HADOOP__YARN__NODE_STATE_PROTO__NS_REBOOTED = 6
} Hadoop__Yarn__NodeStateProto;
typedef enum _Hadoop__Yarn__AMCommandProto {
  HADOOP__YARN__AMCOMMAND_PROTO__AM_RESYNC = 1,
  HADOOP__YARN__AMCOMMAND_PROTO__AM_SHUTDOWN = 2
} Hadoop__Yarn__AMCommandProto;
typedef enum _Hadoop__Yarn__ApplicationAccessTypeProto {
  HADOOP__YARN__APPLICATION_ACCESS_TYPE_PROTO__APPACCESS_VIEW_APP = 1,
  HADOOP__YARN__APPLICATION_ACCESS_TYPE_PROTO__APPACCESS_MODIFY_APP = 2
} Hadoop__Yarn__ApplicationAccessTypeProto;
typedef enum _Hadoop__Yarn__QueueStateProto {
  HADOOP__YARN__QUEUE_STATE_PROTO__Q_STOPPED = 1,
  HADOOP__YARN__QUEUE_STATE_PROTO__Q_RUNNING = 2
} Hadoop__Yarn__QueueStateProto;
typedef enum _Hadoop__Yarn__QueueACLProto {
  HADOOP__YARN__QUEUE_ACLPROTO__QACL_SUBMIT_APPLICATIONS = 1,
  HADOOP__YARN__QUEUE_ACLPROTO__QACL_ADMINISTER_QUEUE = 2
} Hadoop__Yarn__QueueACLProto;
typedef enum _Hadoop__Yarn__ContainerExitStatusProto {
  HADOOP__YARN__CONTAINER_EXIT_STATUS_PROTO__SUCCESS = 0,
  HADOOP__YARN__CONTAINER_EXIT_STATUS_PROTO__INVALID = -1000,
  HADOOP__YARN__CONTAINER_EXIT_STATUS_PROTO__ABORTED = -100,
  HADOOP__YARN__CONTAINER_EXIT_STATUS_PROTO__DISKS_FAILED = -101
} Hadoop__Yarn__ContainerExitStatusProto;

/* --- messages --- */

struct  _Hadoop__Yarn__SerializedExceptionProto
{
  ProtobufCMessage base;
  char *message;
  char *trace;
  char *class_name;
  Hadoop__Yarn__SerializedExceptionProto *cause;
};
#define HADOOP__YARN__SERIALIZED_EXCEPTION_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__serialized_exception_proto__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Hadoop__Yarn__ApplicationIdProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  int32_t id;
  protobuf_c_boolean has_cluster_timestamp;
  int64_t cluster_timestamp;
};
#define HADOOP__YARN__APPLICATION_ID_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_id_proto__descriptor) \
    , 0,0, 0,0 }


struct  _Hadoop__Yarn__ApplicationAttemptIdProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *application_id;
  protobuf_c_boolean has_attemptid;
  int32_t attemptid;
};
#define HADOOP__YARN__APPLICATION_ATTEMPT_ID_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_attempt_id_proto__descriptor) \
    , NULL, 0,0 }


struct  _Hadoop__Yarn__ContainerIdProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *app_id;
  Hadoop__Yarn__ApplicationAttemptIdProto *app_attempt_id;
  protobuf_c_boolean has_id;
  int32_t id;
};
#define HADOOP__YARN__CONTAINER_ID_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__container_id_proto__descriptor) \
    , NULL, NULL, 0,0 }


struct  _Hadoop__Yarn__ResourceProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_memory;
  int32_t memory;
  protobuf_c_boolean has_virtual_cores;
  int32_t virtual_cores;
};
#define HADOOP__YARN__RESOURCE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__resource_proto__descriptor) \
    , 0,0, 0,0 }


struct  _Hadoop__Yarn__PriorityProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_priority;
  int32_t priority;
};
#define HADOOP__YARN__PRIORITY_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__priority_proto__descriptor) \
    , 0,0 }


struct  _Hadoop__Yarn__ContainerProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *id;
  Hadoop__Yarn__NodeIdProto *nodeid;
  char *node_http_address;
  Hadoop__Yarn__ResourceProto *resource;
  Hadoop__Yarn__PriorityProto *priority;
  Hadoop__Common__TokenProto *container_token;
};
#define HADOOP__YARN__CONTAINER_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__container_proto__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Hadoop__Yarn__URLProto
{
  ProtobufCMessage base;
  char *scheme;
  char *host;
  protobuf_c_boolean has_port;
  int32_t port;
  char *file;
  char *userinfo;
};
#define HADOOP__YARN__URLPROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__urlproto__descriptor) \
    , NULL, NULL, 0,0, NULL, NULL }


struct  _Hadoop__Yarn__LocalResourceProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__URLProto *resource;
  protobuf_c_boolean has_size;
  int64_t size;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
  protobuf_c_boolean has_type;
  Hadoop__Yarn__LocalResourceTypeProto type;
  protobuf_c_boolean has_visibility;
  Hadoop__Yarn__LocalResourceVisibilityProto visibility;
  char *pattern;
};
#define HADOOP__YARN__LOCAL_RESOURCE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__local_resource_proto__descriptor) \
    , NULL, 0,0, 0,0, 0,0, 0,0, NULL }


struct  _Hadoop__Yarn__ApplicationResourceUsageReportProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_used_containers;
  int32_t num_used_containers;
  protobuf_c_boolean has_num_reserved_containers;
  int32_t num_reserved_containers;
  Hadoop__Yarn__ResourceProto *used_resources;
  Hadoop__Yarn__ResourceProto *reserved_resources;
  Hadoop__Yarn__ResourceProto *needed_resources;
};
#define HADOOP__YARN__APPLICATION_RESOURCE_USAGE_REPORT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_resource_usage_report_proto__descriptor) \
    , 0,0, 0,0, NULL, NULL, NULL }


struct  _Hadoop__Yarn__ApplicationReportProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *applicationid;
  char *user;
  char *queue;
  char *name;
  char *host;
  protobuf_c_boolean has_rpc_port;
  int32_t rpc_port;
  Hadoop__Common__TokenProto *client_to_am_token;
  protobuf_c_boolean has_yarn_application_state;
  Hadoop__Yarn__YarnApplicationStateProto yarn_application_state;
  char *trackingurl;
  char *diagnostics;
  protobuf_c_boolean has_starttime;
  int64_t starttime;
  protobuf_c_boolean has_finishtime;
  int64_t finishtime;
  protobuf_c_boolean has_final_application_status;
  Hadoop__Yarn__FinalApplicationStatusProto final_application_status;
  Hadoop__Yarn__ApplicationResourceUsageReportProto *app_resource_usage;
  char *originaltrackingurl;
  Hadoop__Yarn__ApplicationAttemptIdProto *currentapplicationattemptid;
  protobuf_c_boolean has_progress;
  float progress;
  char *applicationtype;
  Hadoop__Common__TokenProto *am_rm_token;
};
extern char hadoop__yarn__application_report_proto__diagnostics__default_value[];
#define HADOOP__YARN__APPLICATION_REPORT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_report_proto__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,0, NULL, 0,0, NULL, hadoop__yarn__application_report_proto__diagnostics__default_value, 0,0, 0,0, 0,0, NULL, NULL, NULL, 0,0, NULL, NULL }


struct  _Hadoop__Yarn__NodeIdProto
{
  ProtobufCMessage base;
  char *host;
  protobuf_c_boolean has_port;
  int32_t port;
};
#define HADOOP__YARN__NODE_ID_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__node_id_proto__descriptor) \
    , NULL, 0,0 }


struct  _Hadoop__Yarn__NodeReportProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__NodeIdProto *nodeid;
  char *httpaddress;
  char *rackname;
  Hadoop__Yarn__ResourceProto *used;
  Hadoop__Yarn__ResourceProto *capability;
  protobuf_c_boolean has_numcontainers;
  int32_t numcontainers;
  protobuf_c_boolean has_node_state;
  Hadoop__Yarn__NodeStateProto node_state;
  char *health_report;
  protobuf_c_boolean has_last_health_report_time;
  int64_t last_health_report_time;
};
#define HADOOP__YARN__NODE_REPORT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__node_report_proto__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,0, 0,0, NULL, 0,0 }


struct  _Hadoop__Yarn__ResourceRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__PriorityProto *priority;
  char *resource_name;
  Hadoop__Yarn__ResourceProto *capability;
  protobuf_c_boolean has_num_containers;
  int32_t num_containers;
  protobuf_c_boolean has_relax_locality;
  protobuf_c_boolean relax_locality;
};
#define HADOOP__YARN__RESOURCE_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__resource_request_proto__descriptor) \
    , NULL, NULL, NULL, 0,0, 0,1 }


struct  _Hadoop__Yarn__PreemptionMessageProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__StrictPreemptionContractProto *strictcontract;
  Hadoop__Yarn__PreemptionContractProto *contract;
};
#define HADOOP__YARN__PREEMPTION_MESSAGE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__preemption_message_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__StrictPreemptionContractProto
{
  ProtobufCMessage base;
  size_t n_container;
  Hadoop__Yarn__PreemptionContainerProto **container;
};
#define HADOOP__YARN__STRICT_PREEMPTION_CONTRACT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__strict_preemption_contract_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__PreemptionContractProto
{
  ProtobufCMessage base;
  size_t n_resource;
  Hadoop__Yarn__PreemptionResourceRequestProto **resource;
  size_t n_container;
  Hadoop__Yarn__PreemptionContainerProto **container;
};
#define HADOOP__YARN__PREEMPTION_CONTRACT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__preemption_contract_proto__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__PreemptionContainerProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *id;
};
#define HADOOP__YARN__PREEMPTION_CONTAINER_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__preemption_container_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__PreemptionResourceRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ResourceRequestProto *resource;
};
#define HADOOP__YARN__PREEMPTION_RESOURCE_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__preemption_resource_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__ResourceBlacklistRequestProto
{
  ProtobufCMessage base;
  size_t n_blacklist_additions;
  char **blacklist_additions;
  size_t n_blacklist_removals;
  char **blacklist_removals;
};
#define HADOOP__YARN__RESOURCE_BLACKLIST_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__resource_blacklist_request_proto__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__ApplicationSubmissionContextProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *application_id;
  char *application_name;
  char *queue;
  Hadoop__Yarn__PriorityProto *priority;
  Hadoop__Yarn__ContainerLaunchContextProto *am_container_spec;
  protobuf_c_boolean has_cancel_tokens_when_complete;
  protobuf_c_boolean cancel_tokens_when_complete;
  protobuf_c_boolean has_unmanaged_am;
  protobuf_c_boolean unmanaged_am;
  protobuf_c_boolean has_maxappattempts;
  int32_t maxappattempts;
  Hadoop__Yarn__ResourceProto *resource;
  char *applicationtype;
};
extern char hadoop__yarn__application_submission_context_proto__application_name__default_value[];
extern char hadoop__yarn__application_submission_context_proto__queue__default_value[];
extern char hadoop__yarn__application_submission_context_proto__application_type__default_value[];
#define HADOOP__YARN__APPLICATION_SUBMISSION_CONTEXT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_submission_context_proto__descriptor) \
    , NULL, hadoop__yarn__application_submission_context_proto__application_name__default_value, hadoop__yarn__application_submission_context_proto__queue__default_value, NULL, NULL, 0,1, 0,0, 0,0, NULL, hadoop__yarn__application_submission_context_proto__application_type__default_value }


struct  _Hadoop__Yarn__ApplicationACLMapProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_accesstype;
  Hadoop__Yarn__ApplicationAccessTypeProto accesstype;
  char *acl;
};
extern char hadoop__yarn__application_aclmap_proto__acl__default_value[];
#define HADOOP__YARN__APPLICATION_ACLMAP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_aclmap_proto__descriptor) \
    , 0,0, hadoop__yarn__application_aclmap_proto__acl__default_value }


struct  _Hadoop__Yarn__YarnClusterMetricsProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_node_managers;
  int32_t num_node_managers;
};
#define HADOOP__YARN__YARN_CLUSTER_METRICS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__yarn_cluster_metrics_proto__descriptor) \
    , 0,0 }


struct  _Hadoop__Yarn__QueueInfoProto
{
  ProtobufCMessage base;
  char *queuename;
  protobuf_c_boolean has_capacity;
  float capacity;
  protobuf_c_boolean has_maximumcapacity;
  float maximumcapacity;
  protobuf_c_boolean has_currentcapacity;
  float currentcapacity;
  protobuf_c_boolean has_state;
  Hadoop__Yarn__QueueStateProto state;
  size_t n_childqueues;
  Hadoop__Yarn__QueueInfoProto **childqueues;
  size_t n_applications;
  Hadoop__Yarn__ApplicationReportProto **applications;
};
#define HADOOP__YARN__QUEUE_INFO_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__queue_info_proto__descriptor) \
    , NULL, 0,0, 0,0, 0,0, 0,0, 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__QueueUserACLInfoProto
{
  ProtobufCMessage base;
  char *queuename;
  size_t n_useracls;
  Hadoop__Yarn__QueueACLProto *useracls;
};
#define HADOOP__YARN__QUEUE_USER_ACLINFO_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__queue_user_aclinfo_proto__descriptor) \
    , NULL, 0,NULL }


struct  _Hadoop__Yarn__ContainerLaunchContextProto
{
  ProtobufCMessage base;
  size_t n_localresources;
  Hadoop__Yarn__StringLocalResourceMapProto **localresources;
  protobuf_c_boolean has_tokens;
  ProtobufCBinaryData tokens;
  size_t n_service_data;
  Hadoop__Yarn__StringBytesMapProto **service_data;
  size_t n_environment;
  Hadoop__Yarn__StringStringMapProto **environment;
  size_t n_command;
  char **command;
  size_t n_application_acls;
  Hadoop__Yarn__ApplicationACLMapProto **application_acls;
};
#define HADOOP__YARN__CONTAINER_LAUNCH_CONTEXT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__container_launch_context_proto__descriptor) \
    , 0,NULL, 0,{0,NULL}, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__ContainerStatusProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *container_id;
  protobuf_c_boolean has_state;
  Hadoop__Yarn__ContainerStateProto state;
  char *diagnostics;
  protobuf_c_boolean has_exit_status;
  int32_t exit_status;
};
extern char hadoop__yarn__container_status_proto__diagnostics__default_value[];
#define HADOOP__YARN__CONTAINER_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__container_status_proto__descriptor) \
    , NULL, 0,0, hadoop__yarn__container_status_proto__diagnostics__default_value, 0,-1000 }


struct  _Hadoop__Yarn__StringLocalResourceMapProto
{
  ProtobufCMessage base;
  char *key;
  Hadoop__Yarn__LocalResourceProto *value;
};
#define HADOOP__YARN__STRING_LOCAL_RESOURCE_MAP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__string_local_resource_map_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__StringStringMapProto
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define HADOOP__YARN__STRING_STRING_MAP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__string_string_map_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__StringBytesMapProto
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_value;
  ProtobufCBinaryData value;
};
#define HADOOP__YARN__STRING_BYTES_MAP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__string_bytes_map_proto__descriptor) \
    , NULL, 0,{0,NULL} }


/* Hadoop__Yarn__SerializedExceptionProto methods */
void   hadoop__yarn__serialized_exception_proto__init
                     (Hadoop__Yarn__SerializedExceptionProto         *message);
size_t hadoop__yarn__serialized_exception_proto__get_packed_size
                     (const Hadoop__Yarn__SerializedExceptionProto   *message);
size_t hadoop__yarn__serialized_exception_proto__pack
                     (const Hadoop__Yarn__SerializedExceptionProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__serialized_exception_proto__pack_to_buffer
                     (const Hadoop__Yarn__SerializedExceptionProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__SerializedExceptionProto *
       hadoop__yarn__serialized_exception_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__serialized_exception_proto__free_unpacked
                     (Hadoop__Yarn__SerializedExceptionProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationIdProto methods */
void   hadoop__yarn__application_id_proto__init
                     (Hadoop__Yarn__ApplicationIdProto         *message);
size_t hadoop__yarn__application_id_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationIdProto   *message);
size_t hadoop__yarn__application_id_proto__pack
                     (const Hadoop__Yarn__ApplicationIdProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_id_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationIdProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationIdProto *
       hadoop__yarn__application_id_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_id_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationIdProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationAttemptIdProto methods */
void   hadoop__yarn__application_attempt_id_proto__init
                     (Hadoop__Yarn__ApplicationAttemptIdProto         *message);
size_t hadoop__yarn__application_attempt_id_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationAttemptIdProto   *message);
size_t hadoop__yarn__application_attempt_id_proto__pack
                     (const Hadoop__Yarn__ApplicationAttemptIdProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_attempt_id_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationAttemptIdProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationAttemptIdProto *
       hadoop__yarn__application_attempt_id_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_attempt_id_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationAttemptIdProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ContainerIdProto methods */
void   hadoop__yarn__container_id_proto__init
                     (Hadoop__Yarn__ContainerIdProto         *message);
size_t hadoop__yarn__container_id_proto__get_packed_size
                     (const Hadoop__Yarn__ContainerIdProto   *message);
size_t hadoop__yarn__container_id_proto__pack
                     (const Hadoop__Yarn__ContainerIdProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__container_id_proto__pack_to_buffer
                     (const Hadoop__Yarn__ContainerIdProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ContainerIdProto *
       hadoop__yarn__container_id_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__container_id_proto__free_unpacked
                     (Hadoop__Yarn__ContainerIdProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ResourceProto methods */
void   hadoop__yarn__resource_proto__init
                     (Hadoop__Yarn__ResourceProto         *message);
size_t hadoop__yarn__resource_proto__get_packed_size
                     (const Hadoop__Yarn__ResourceProto   *message);
size_t hadoop__yarn__resource_proto__pack
                     (const Hadoop__Yarn__ResourceProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__resource_proto__pack_to_buffer
                     (const Hadoop__Yarn__ResourceProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ResourceProto *
       hadoop__yarn__resource_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__resource_proto__free_unpacked
                     (Hadoop__Yarn__ResourceProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__PriorityProto methods */
void   hadoop__yarn__priority_proto__init
                     (Hadoop__Yarn__PriorityProto         *message);
size_t hadoop__yarn__priority_proto__get_packed_size
                     (const Hadoop__Yarn__PriorityProto   *message);
size_t hadoop__yarn__priority_proto__pack
                     (const Hadoop__Yarn__PriorityProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__priority_proto__pack_to_buffer
                     (const Hadoop__Yarn__PriorityProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__PriorityProto *
       hadoop__yarn__priority_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__priority_proto__free_unpacked
                     (Hadoop__Yarn__PriorityProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ContainerProto methods */
void   hadoop__yarn__container_proto__init
                     (Hadoop__Yarn__ContainerProto         *message);
size_t hadoop__yarn__container_proto__get_packed_size
                     (const Hadoop__Yarn__ContainerProto   *message);
size_t hadoop__yarn__container_proto__pack
                     (const Hadoop__Yarn__ContainerProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__container_proto__pack_to_buffer
                     (const Hadoop__Yarn__ContainerProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ContainerProto *
       hadoop__yarn__container_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__container_proto__free_unpacked
                     (Hadoop__Yarn__ContainerProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__URLProto methods */
void   hadoop__yarn__urlproto__init
                     (Hadoop__Yarn__URLProto         *message);
size_t hadoop__yarn__urlproto__get_packed_size
                     (const Hadoop__Yarn__URLProto   *message);
size_t hadoop__yarn__urlproto__pack
                     (const Hadoop__Yarn__URLProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__urlproto__pack_to_buffer
                     (const Hadoop__Yarn__URLProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__URLProto *
       hadoop__yarn__urlproto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__urlproto__free_unpacked
                     (Hadoop__Yarn__URLProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__LocalResourceProto methods */
void   hadoop__yarn__local_resource_proto__init
                     (Hadoop__Yarn__LocalResourceProto         *message);
size_t hadoop__yarn__local_resource_proto__get_packed_size
                     (const Hadoop__Yarn__LocalResourceProto   *message);
size_t hadoop__yarn__local_resource_proto__pack
                     (const Hadoop__Yarn__LocalResourceProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__local_resource_proto__pack_to_buffer
                     (const Hadoop__Yarn__LocalResourceProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__LocalResourceProto *
       hadoop__yarn__local_resource_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__local_resource_proto__free_unpacked
                     (Hadoop__Yarn__LocalResourceProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationResourceUsageReportProto methods */
void   hadoop__yarn__application_resource_usage_report_proto__init
                     (Hadoop__Yarn__ApplicationResourceUsageReportProto         *message);
size_t hadoop__yarn__application_resource_usage_report_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationResourceUsageReportProto   *message);
size_t hadoop__yarn__application_resource_usage_report_proto__pack
                     (const Hadoop__Yarn__ApplicationResourceUsageReportProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_resource_usage_report_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationResourceUsageReportProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationResourceUsageReportProto *
       hadoop__yarn__application_resource_usage_report_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_resource_usage_report_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationResourceUsageReportProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationReportProto methods */
void   hadoop__yarn__application_report_proto__init
                     (Hadoop__Yarn__ApplicationReportProto         *message);
size_t hadoop__yarn__application_report_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationReportProto   *message);
size_t hadoop__yarn__application_report_proto__pack
                     (const Hadoop__Yarn__ApplicationReportProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_report_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationReportProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationReportProto *
       hadoop__yarn__application_report_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_report_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationReportProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__NodeIdProto methods */
void   hadoop__yarn__node_id_proto__init
                     (Hadoop__Yarn__NodeIdProto         *message);
size_t hadoop__yarn__node_id_proto__get_packed_size
                     (const Hadoop__Yarn__NodeIdProto   *message);
size_t hadoop__yarn__node_id_proto__pack
                     (const Hadoop__Yarn__NodeIdProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__node_id_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeIdProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__NodeIdProto *
       hadoop__yarn__node_id_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__node_id_proto__free_unpacked
                     (Hadoop__Yarn__NodeIdProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__NodeReportProto methods */
void   hadoop__yarn__node_report_proto__init
                     (Hadoop__Yarn__NodeReportProto         *message);
size_t hadoop__yarn__node_report_proto__get_packed_size
                     (const Hadoop__Yarn__NodeReportProto   *message);
size_t hadoop__yarn__node_report_proto__pack
                     (const Hadoop__Yarn__NodeReportProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__node_report_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeReportProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__NodeReportProto *
       hadoop__yarn__node_report_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__node_report_proto__free_unpacked
                     (Hadoop__Yarn__NodeReportProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ResourceRequestProto methods */
void   hadoop__yarn__resource_request_proto__init
                     (Hadoop__Yarn__ResourceRequestProto         *message);
size_t hadoop__yarn__resource_request_proto__get_packed_size
                     (const Hadoop__Yarn__ResourceRequestProto   *message);
size_t hadoop__yarn__resource_request_proto__pack
                     (const Hadoop__Yarn__ResourceRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__resource_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__ResourceRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ResourceRequestProto *
       hadoop__yarn__resource_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__resource_request_proto__free_unpacked
                     (Hadoop__Yarn__ResourceRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__PreemptionMessageProto methods */
void   hadoop__yarn__preemption_message_proto__init
                     (Hadoop__Yarn__PreemptionMessageProto         *message);
size_t hadoop__yarn__preemption_message_proto__get_packed_size
                     (const Hadoop__Yarn__PreemptionMessageProto   *message);
size_t hadoop__yarn__preemption_message_proto__pack
                     (const Hadoop__Yarn__PreemptionMessageProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__preemption_message_proto__pack_to_buffer
                     (const Hadoop__Yarn__PreemptionMessageProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__PreemptionMessageProto *
       hadoop__yarn__preemption_message_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__preemption_message_proto__free_unpacked
                     (Hadoop__Yarn__PreemptionMessageProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StrictPreemptionContractProto methods */
void   hadoop__yarn__strict_preemption_contract_proto__init
                     (Hadoop__Yarn__StrictPreemptionContractProto         *message);
size_t hadoop__yarn__strict_preemption_contract_proto__get_packed_size
                     (const Hadoop__Yarn__StrictPreemptionContractProto   *message);
size_t hadoop__yarn__strict_preemption_contract_proto__pack
                     (const Hadoop__Yarn__StrictPreemptionContractProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__strict_preemption_contract_proto__pack_to_buffer
                     (const Hadoop__Yarn__StrictPreemptionContractProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StrictPreemptionContractProto *
       hadoop__yarn__strict_preemption_contract_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__strict_preemption_contract_proto__free_unpacked
                     (Hadoop__Yarn__StrictPreemptionContractProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__PreemptionContractProto methods */
void   hadoop__yarn__preemption_contract_proto__init
                     (Hadoop__Yarn__PreemptionContractProto         *message);
size_t hadoop__yarn__preemption_contract_proto__get_packed_size
                     (const Hadoop__Yarn__PreemptionContractProto   *message);
size_t hadoop__yarn__preemption_contract_proto__pack
                     (const Hadoop__Yarn__PreemptionContractProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__preemption_contract_proto__pack_to_buffer
                     (const Hadoop__Yarn__PreemptionContractProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__PreemptionContractProto *
       hadoop__yarn__preemption_contract_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__preemption_contract_proto__free_unpacked
                     (Hadoop__Yarn__PreemptionContractProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__PreemptionContainerProto methods */
void   hadoop__yarn__preemption_container_proto__init
                     (Hadoop__Yarn__PreemptionContainerProto         *message);
size_t hadoop__yarn__preemption_container_proto__get_packed_size
                     (const Hadoop__Yarn__PreemptionContainerProto   *message);
size_t hadoop__yarn__preemption_container_proto__pack
                     (const Hadoop__Yarn__PreemptionContainerProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__preemption_container_proto__pack_to_buffer
                     (const Hadoop__Yarn__PreemptionContainerProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__PreemptionContainerProto *
       hadoop__yarn__preemption_container_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__preemption_container_proto__free_unpacked
                     (Hadoop__Yarn__PreemptionContainerProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__PreemptionResourceRequestProto methods */
void   hadoop__yarn__preemption_resource_request_proto__init
                     (Hadoop__Yarn__PreemptionResourceRequestProto         *message);
size_t hadoop__yarn__preemption_resource_request_proto__get_packed_size
                     (const Hadoop__Yarn__PreemptionResourceRequestProto   *message);
size_t hadoop__yarn__preemption_resource_request_proto__pack
                     (const Hadoop__Yarn__PreemptionResourceRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__preemption_resource_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__PreemptionResourceRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__PreemptionResourceRequestProto *
       hadoop__yarn__preemption_resource_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__preemption_resource_request_proto__free_unpacked
                     (Hadoop__Yarn__PreemptionResourceRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ResourceBlacklistRequestProto methods */
void   hadoop__yarn__resource_blacklist_request_proto__init
                     (Hadoop__Yarn__ResourceBlacklistRequestProto         *message);
size_t hadoop__yarn__resource_blacklist_request_proto__get_packed_size
                     (const Hadoop__Yarn__ResourceBlacklistRequestProto   *message);
size_t hadoop__yarn__resource_blacklist_request_proto__pack
                     (const Hadoop__Yarn__ResourceBlacklistRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__resource_blacklist_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__ResourceBlacklistRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ResourceBlacklistRequestProto *
       hadoop__yarn__resource_blacklist_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__resource_blacklist_request_proto__free_unpacked
                     (Hadoop__Yarn__ResourceBlacklistRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationSubmissionContextProto methods */
void   hadoop__yarn__application_submission_context_proto__init
                     (Hadoop__Yarn__ApplicationSubmissionContextProto         *message);
size_t hadoop__yarn__application_submission_context_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationSubmissionContextProto   *message);
size_t hadoop__yarn__application_submission_context_proto__pack
                     (const Hadoop__Yarn__ApplicationSubmissionContextProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_submission_context_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationSubmissionContextProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationSubmissionContextProto *
       hadoop__yarn__application_submission_context_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_submission_context_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationSubmissionContextProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationACLMapProto methods */
void   hadoop__yarn__application_aclmap_proto__init
                     (Hadoop__Yarn__ApplicationACLMapProto         *message);
size_t hadoop__yarn__application_aclmap_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationACLMapProto   *message);
size_t hadoop__yarn__application_aclmap_proto__pack
                     (const Hadoop__Yarn__ApplicationACLMapProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_aclmap_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationACLMapProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationACLMapProto *
       hadoop__yarn__application_aclmap_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_aclmap_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationACLMapProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__YarnClusterMetricsProto methods */
void   hadoop__yarn__yarn_cluster_metrics_proto__init
                     (Hadoop__Yarn__YarnClusterMetricsProto         *message);
size_t hadoop__yarn__yarn_cluster_metrics_proto__get_packed_size
                     (const Hadoop__Yarn__YarnClusterMetricsProto   *message);
size_t hadoop__yarn__yarn_cluster_metrics_proto__pack
                     (const Hadoop__Yarn__YarnClusterMetricsProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__yarn_cluster_metrics_proto__pack_to_buffer
                     (const Hadoop__Yarn__YarnClusterMetricsProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__YarnClusterMetricsProto *
       hadoop__yarn__yarn_cluster_metrics_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__yarn_cluster_metrics_proto__free_unpacked
                     (Hadoop__Yarn__YarnClusterMetricsProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__QueueInfoProto methods */
void   hadoop__yarn__queue_info_proto__init
                     (Hadoop__Yarn__QueueInfoProto         *message);
size_t hadoop__yarn__queue_info_proto__get_packed_size
                     (const Hadoop__Yarn__QueueInfoProto   *message);
size_t hadoop__yarn__queue_info_proto__pack
                     (const Hadoop__Yarn__QueueInfoProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__queue_info_proto__pack_to_buffer
                     (const Hadoop__Yarn__QueueInfoProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__QueueInfoProto *
       hadoop__yarn__queue_info_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__queue_info_proto__free_unpacked
                     (Hadoop__Yarn__QueueInfoProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__QueueUserACLInfoProto methods */
void   hadoop__yarn__queue_user_aclinfo_proto__init
                     (Hadoop__Yarn__QueueUserACLInfoProto         *message);
size_t hadoop__yarn__queue_user_aclinfo_proto__get_packed_size
                     (const Hadoop__Yarn__QueueUserACLInfoProto   *message);
size_t hadoop__yarn__queue_user_aclinfo_proto__pack
                     (const Hadoop__Yarn__QueueUserACLInfoProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__queue_user_aclinfo_proto__pack_to_buffer
                     (const Hadoop__Yarn__QueueUserACLInfoProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__QueueUserACLInfoProto *
       hadoop__yarn__queue_user_aclinfo_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__queue_user_aclinfo_proto__free_unpacked
                     (Hadoop__Yarn__QueueUserACLInfoProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ContainerLaunchContextProto methods */
void   hadoop__yarn__container_launch_context_proto__init
                     (Hadoop__Yarn__ContainerLaunchContextProto         *message);
size_t hadoop__yarn__container_launch_context_proto__get_packed_size
                     (const Hadoop__Yarn__ContainerLaunchContextProto   *message);
size_t hadoop__yarn__container_launch_context_proto__pack
                     (const Hadoop__Yarn__ContainerLaunchContextProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__container_launch_context_proto__pack_to_buffer
                     (const Hadoop__Yarn__ContainerLaunchContextProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ContainerLaunchContextProto *
       hadoop__yarn__container_launch_context_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__container_launch_context_proto__free_unpacked
                     (Hadoop__Yarn__ContainerLaunchContextProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ContainerStatusProto methods */
void   hadoop__yarn__container_status_proto__init
                     (Hadoop__Yarn__ContainerStatusProto         *message);
size_t hadoop__yarn__container_status_proto__get_packed_size
                     (const Hadoop__Yarn__ContainerStatusProto   *message);
size_t hadoop__yarn__container_status_proto__pack
                     (const Hadoop__Yarn__ContainerStatusProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__container_status_proto__pack_to_buffer
                     (const Hadoop__Yarn__ContainerStatusProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ContainerStatusProto *
       hadoop__yarn__container_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__container_status_proto__free_unpacked
                     (Hadoop__Yarn__ContainerStatusProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StringLocalResourceMapProto methods */
void   hadoop__yarn__string_local_resource_map_proto__init
                     (Hadoop__Yarn__StringLocalResourceMapProto         *message);
size_t hadoop__yarn__string_local_resource_map_proto__get_packed_size
                     (const Hadoop__Yarn__StringLocalResourceMapProto   *message);
size_t hadoop__yarn__string_local_resource_map_proto__pack
                     (const Hadoop__Yarn__StringLocalResourceMapProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__string_local_resource_map_proto__pack_to_buffer
                     (const Hadoop__Yarn__StringLocalResourceMapProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StringLocalResourceMapProto *
       hadoop__yarn__string_local_resource_map_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__string_local_resource_map_proto__free_unpacked
                     (Hadoop__Yarn__StringLocalResourceMapProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StringStringMapProto methods */
void   hadoop__yarn__string_string_map_proto__init
                     (Hadoop__Yarn__StringStringMapProto         *message);
size_t hadoop__yarn__string_string_map_proto__get_packed_size
                     (const Hadoop__Yarn__StringStringMapProto   *message);
size_t hadoop__yarn__string_string_map_proto__pack
                     (const Hadoop__Yarn__StringStringMapProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__string_string_map_proto__pack_to_buffer
                     (const Hadoop__Yarn__StringStringMapProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StringStringMapProto *
       hadoop__yarn__string_string_map_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__string_string_map_proto__free_unpacked
                     (Hadoop__Yarn__StringStringMapProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StringBytesMapProto methods */
void   hadoop__yarn__string_bytes_map_proto__init
                     (Hadoop__Yarn__StringBytesMapProto         *message);
size_t hadoop__yarn__string_bytes_map_proto__get_packed_size
                     (const Hadoop__Yarn__StringBytesMapProto   *message);
size_t hadoop__yarn__string_bytes_map_proto__pack
                     (const Hadoop__Yarn__StringBytesMapProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__string_bytes_map_proto__pack_to_buffer
                     (const Hadoop__Yarn__StringBytesMapProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StringBytesMapProto *
       hadoop__yarn__string_bytes_map_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__string_bytes_map_proto__free_unpacked
                     (Hadoop__Yarn__StringBytesMapProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Yarn__SerializedExceptionProto_Closure)
                 (const Hadoop__Yarn__SerializedExceptionProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationIdProto_Closure)
                 (const Hadoop__Yarn__ApplicationIdProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationAttemptIdProto_Closure)
                 (const Hadoop__Yarn__ApplicationAttemptIdProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ContainerIdProto_Closure)
                 (const Hadoop__Yarn__ContainerIdProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ResourceProto_Closure)
                 (const Hadoop__Yarn__ResourceProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__PriorityProto_Closure)
                 (const Hadoop__Yarn__PriorityProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ContainerProto_Closure)
                 (const Hadoop__Yarn__ContainerProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__URLProto_Closure)
                 (const Hadoop__Yarn__URLProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__LocalResourceProto_Closure)
                 (const Hadoop__Yarn__LocalResourceProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationResourceUsageReportProto_Closure)
                 (const Hadoop__Yarn__ApplicationResourceUsageReportProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationReportProto_Closure)
                 (const Hadoop__Yarn__ApplicationReportProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__NodeIdProto_Closure)
                 (const Hadoop__Yarn__NodeIdProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__NodeReportProto_Closure)
                 (const Hadoop__Yarn__NodeReportProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ResourceRequestProto_Closure)
                 (const Hadoop__Yarn__ResourceRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__PreemptionMessageProto_Closure)
                 (const Hadoop__Yarn__PreemptionMessageProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StrictPreemptionContractProto_Closure)
                 (const Hadoop__Yarn__StrictPreemptionContractProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__PreemptionContractProto_Closure)
                 (const Hadoop__Yarn__PreemptionContractProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__PreemptionContainerProto_Closure)
                 (const Hadoop__Yarn__PreemptionContainerProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__PreemptionResourceRequestProto_Closure)
                 (const Hadoop__Yarn__PreemptionResourceRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ResourceBlacklistRequestProto_Closure)
                 (const Hadoop__Yarn__ResourceBlacklistRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationSubmissionContextProto_Closure)
                 (const Hadoop__Yarn__ApplicationSubmissionContextProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationACLMapProto_Closure)
                 (const Hadoop__Yarn__ApplicationACLMapProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__YarnClusterMetricsProto_Closure)
                 (const Hadoop__Yarn__YarnClusterMetricsProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__QueueInfoProto_Closure)
                 (const Hadoop__Yarn__QueueInfoProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__QueueUserACLInfoProto_Closure)
                 (const Hadoop__Yarn__QueueUserACLInfoProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ContainerLaunchContextProto_Closure)
                 (const Hadoop__Yarn__ContainerLaunchContextProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ContainerStatusProto_Closure)
                 (const Hadoop__Yarn__ContainerStatusProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StringLocalResourceMapProto_Closure)
                 (const Hadoop__Yarn__StringLocalResourceMapProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StringStringMapProto_Closure)
                 (const Hadoop__Yarn__StringStringMapProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StringBytesMapProto_Closure)
                 (const Hadoop__Yarn__StringBytesMapProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    hadoop__yarn__container_state_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__yarn_application_state_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__final_application_status_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__local_resource_visibility_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__local_resource_type_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__node_state_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__amcommand_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__application_access_type_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__queue_state_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__queue_aclproto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__container_exit_status_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__serialized_exception_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_id_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_attempt_id_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__container_id_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__resource_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__priority_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__container_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__urlproto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__local_resource_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_resource_usage_report_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_report_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__node_id_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__node_report_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__resource_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__preemption_message_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__strict_preemption_contract_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__preemption_contract_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__preemption_container_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__preemption_resource_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__resource_blacklist_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_submission_context_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_aclmap_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__yarn_cluster_metrics_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__queue_info_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__queue_user_aclinfo_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__container_launch_context_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__container_status_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__string_local_resource_map_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__string_string_map_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__string_bytes_map_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fprotos_2eproto__INCLUDED */
