/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_protos.pb-c.h"

typedef struct _Hadoop__Yarn__LocalResourceStatusProto Hadoop__Yarn__LocalResourceStatusProto;
typedef struct _Hadoop__Yarn__LocalizerStatusProto Hadoop__Yarn__LocalizerStatusProto;
typedef struct _Hadoop__Yarn__ResourceLocalizationSpecProto Hadoop__Yarn__ResourceLocalizationSpecProto;
typedef struct _Hadoop__Yarn__LocalizerHeartbeatResponseProto Hadoop__Yarn__LocalizerHeartbeatResponseProto;


/* --- enums --- */

typedef enum _Hadoop__Yarn__ResourceStatusTypeProto {
  HADOOP__YARN__RESOURCE_STATUS_TYPE_PROTO__FETCH_PENDING = 1,
  HADOOP__YARN__RESOURCE_STATUS_TYPE_PROTO__FETCH_SUCCESS = 2,
  HADOOP__YARN__RESOURCE_STATUS_TYPE_PROTO__FETCH_FAILURE = 3
} Hadoop__Yarn__ResourceStatusTypeProto;
typedef enum _Hadoop__Yarn__LocalizerActionProto {
  HADOOP__YARN__LOCALIZER_ACTION_PROTO__LIVE = 1,
  HADOOP__YARN__LOCALIZER_ACTION_PROTO__DIE = 2
} Hadoop__Yarn__LocalizerActionProto;

/* --- messages --- */

struct  _Hadoop__Yarn__LocalResourceStatusProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__LocalResourceProto *resource;
  protobuf_c_boolean has_status;
  Hadoop__Yarn__ResourceStatusTypeProto status;
  Hadoop__Yarn__URLProto *localpath;
  protobuf_c_boolean has_localsize;
  int64_t localsize;
  Hadoop__Yarn__SerializedExceptionProto *exception;
};
#define HADOOP__YARN__LOCAL_RESOURCE_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__local_resource_status_proto__descriptor) \
    , NULL, 0,0, NULL, 0,0, NULL }


struct  _Hadoop__Yarn__LocalizerStatusProto
{
  ProtobufCMessage base;
  char *localizer_id;
  size_t n_resources;
  Hadoop__Yarn__LocalResourceStatusProto **resources;
};
#define HADOOP__YARN__LOCALIZER_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__localizer_status_proto__descriptor) \
    , NULL, 0,NULL }


struct  _Hadoop__Yarn__ResourceLocalizationSpecProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__LocalResourceProto *resource;
  Hadoop__Yarn__URLProto *destination_directory;
};
#define HADOOP__YARN__RESOURCE_LOCALIZATION_SPEC_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__resource_localization_spec_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__LocalizerHeartbeatResponseProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_action;
  Hadoop__Yarn__LocalizerActionProto action;
  size_t n_resources;
  Hadoop__Yarn__ResourceLocalizationSpecProto **resources;
};
#define HADOOP__YARN__LOCALIZER_HEARTBEAT_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__localizer_heartbeat_response_proto__descriptor) \
    , 0,0, 0,NULL }


/* Hadoop__Yarn__LocalResourceStatusProto methods */
void   hadoop__yarn__local_resource_status_proto__init
                     (Hadoop__Yarn__LocalResourceStatusProto         *message);
size_t hadoop__yarn__local_resource_status_proto__get_packed_size
                     (const Hadoop__Yarn__LocalResourceStatusProto   *message);
size_t hadoop__yarn__local_resource_status_proto__pack
                     (const Hadoop__Yarn__LocalResourceStatusProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__local_resource_status_proto__pack_to_buffer
                     (const Hadoop__Yarn__LocalResourceStatusProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__LocalResourceStatusProto *
       hadoop__yarn__local_resource_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__local_resource_status_proto__free_unpacked
                     (Hadoop__Yarn__LocalResourceStatusProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__LocalizerStatusProto methods */
void   hadoop__yarn__localizer_status_proto__init
                     (Hadoop__Yarn__LocalizerStatusProto         *message);
size_t hadoop__yarn__localizer_status_proto__get_packed_size
                     (const Hadoop__Yarn__LocalizerStatusProto   *message);
size_t hadoop__yarn__localizer_status_proto__pack
                     (const Hadoop__Yarn__LocalizerStatusProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__localizer_status_proto__pack_to_buffer
                     (const Hadoop__Yarn__LocalizerStatusProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__LocalizerStatusProto *
       hadoop__yarn__localizer_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__localizer_status_proto__free_unpacked
                     (Hadoop__Yarn__LocalizerStatusProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ResourceLocalizationSpecProto methods */
void   hadoop__yarn__resource_localization_spec_proto__init
                     (Hadoop__Yarn__ResourceLocalizationSpecProto         *message);
size_t hadoop__yarn__resource_localization_spec_proto__get_packed_size
                     (const Hadoop__Yarn__ResourceLocalizationSpecProto   *message);
size_t hadoop__yarn__resource_localization_spec_proto__pack
                     (const Hadoop__Yarn__ResourceLocalizationSpecProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__resource_localization_spec_proto__pack_to_buffer
                     (const Hadoop__Yarn__ResourceLocalizationSpecProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ResourceLocalizationSpecProto *
       hadoop__yarn__resource_localization_spec_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__resource_localization_spec_proto__free_unpacked
                     (Hadoop__Yarn__ResourceLocalizationSpecProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__LocalizerHeartbeatResponseProto methods */
void   hadoop__yarn__localizer_heartbeat_response_proto__init
                     (Hadoop__Yarn__LocalizerHeartbeatResponseProto         *message);
size_t hadoop__yarn__localizer_heartbeat_response_proto__get_packed_size
                     (const Hadoop__Yarn__LocalizerHeartbeatResponseProto   *message);
size_t hadoop__yarn__localizer_heartbeat_response_proto__pack
                     (const Hadoop__Yarn__LocalizerHeartbeatResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__localizer_heartbeat_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__LocalizerHeartbeatResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__LocalizerHeartbeatResponseProto *
       hadoop__yarn__localizer_heartbeat_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__localizer_heartbeat_response_proto__free_unpacked
                     (Hadoop__Yarn__LocalizerHeartbeatResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Yarn__LocalResourceStatusProto_Closure)
                 (const Hadoop__Yarn__LocalResourceStatusProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__LocalizerStatusProto_Closure)
                 (const Hadoop__Yarn__LocalizerStatusProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ResourceLocalizationSpecProto_Closure)
                 (const Hadoop__Yarn__ResourceLocalizationSpecProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__LocalizerHeartbeatResponseProto_Closure)
                 (const Hadoop__Yarn__LocalizerHeartbeatResponseProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    hadoop__yarn__resource_status_type_proto__descriptor;
extern const ProtobufCEnumDescriptor    hadoop__yarn__localizer_action_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__local_resource_status_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__localizer_status_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__resource_localization_spec_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__localizer_heartbeat_response_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fserver_5fnodemanager_5fservice_5fprotos_2eproto__INCLUDED */
