/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_protos.pb-c.h"

typedef struct _Hadoop__Yarn__NodeStatusProto Hadoop__Yarn__NodeStatusProto;
typedef struct _Hadoop__Yarn__MasterKeyProto Hadoop__Yarn__MasterKeyProto;
typedef struct _Hadoop__Yarn__NodeHealthStatusProto Hadoop__Yarn__NodeHealthStatusProto;


/* --- enums --- */

typedef enum _Hadoop__Yarn__NodeActionProto {
  HADOOP__YARN__NODE_ACTION_PROTO__NORMAL = 0,
  HADOOP__YARN__NODE_ACTION_PROTO__RESYNC = 1,
  HADOOP__YARN__NODE_ACTION_PROTO__SHUTDOWN = 2
} Hadoop__Yarn__NodeActionProto;

/* --- messages --- */

struct  _Hadoop__Yarn__NodeStatusProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__NodeIdProto *node_id;
  protobuf_c_boolean has_response_id;
  int32_t response_id;
  size_t n_containersstatuses;
  Hadoop__Yarn__ContainerStatusProto **containersstatuses;
  Hadoop__Yarn__NodeHealthStatusProto *nodehealthstatus;
  size_t n_keep_alive_applications;
  Hadoop__Yarn__ApplicationIdProto **keep_alive_applications;
};
#define HADOOP__YARN__NODE_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__node_status_proto__descriptor) \
    , NULL, 0,0, 0,NULL, NULL, 0,NULL }


struct  _Hadoop__Yarn__MasterKeyProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_key_id;
  int32_t key_id;
  protobuf_c_boolean has_bytes;
  ProtobufCBinaryData bytes;
};
#define HADOOP__YARN__MASTER_KEY_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__master_key_proto__descriptor) \
    , 0,0, 0,{0,NULL} }


struct  _Hadoop__Yarn__NodeHealthStatusProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_is_node_healthy;
  protobuf_c_boolean is_node_healthy;
  char *health_report;
  protobuf_c_boolean has_last_health_report_time;
  int64_t last_health_report_time;
};
#define HADOOP__YARN__NODE_HEALTH_STATUS_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__node_health_status_proto__descriptor) \
    , 0,0, NULL, 0,0 }


/* Hadoop__Yarn__NodeStatusProto methods */
void   hadoop__yarn__node_status_proto__init
                     (Hadoop__Yarn__NodeStatusProto         *message);
size_t hadoop__yarn__node_status_proto__get_packed_size
                     (const Hadoop__Yarn__NodeStatusProto   *message);
size_t hadoop__yarn__node_status_proto__pack
                     (const Hadoop__Yarn__NodeStatusProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__node_status_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeStatusProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__NodeStatusProto *
       hadoop__yarn__node_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__node_status_proto__free_unpacked
                     (Hadoop__Yarn__NodeStatusProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__MasterKeyProto methods */
void   hadoop__yarn__master_key_proto__init
                     (Hadoop__Yarn__MasterKeyProto         *message);
size_t hadoop__yarn__master_key_proto__get_packed_size
                     (const Hadoop__Yarn__MasterKeyProto   *message);
size_t hadoop__yarn__master_key_proto__pack
                     (const Hadoop__Yarn__MasterKeyProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__master_key_proto__pack_to_buffer
                     (const Hadoop__Yarn__MasterKeyProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__MasterKeyProto *
       hadoop__yarn__master_key_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__master_key_proto__free_unpacked
                     (Hadoop__Yarn__MasterKeyProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__NodeHealthStatusProto methods */
void   hadoop__yarn__node_health_status_proto__init
                     (Hadoop__Yarn__NodeHealthStatusProto         *message);
size_t hadoop__yarn__node_health_status_proto__get_packed_size
                     (const Hadoop__Yarn__NodeHealthStatusProto   *message);
size_t hadoop__yarn__node_health_status_proto__pack
                     (const Hadoop__Yarn__NodeHealthStatusProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__node_health_status_proto__pack_to_buffer
                     (const Hadoop__Yarn__NodeHealthStatusProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__NodeHealthStatusProto *
       hadoop__yarn__node_health_status_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__node_health_status_proto__free_unpacked
                     (Hadoop__Yarn__NodeHealthStatusProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Yarn__NodeStatusProto_Closure)
                 (const Hadoop__Yarn__NodeStatusProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__MasterKeyProto_Closure)
                 (const Hadoop__Yarn__MasterKeyProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__NodeHealthStatusProto_Closure)
                 (const Hadoop__Yarn__NodeHealthStatusProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    hadoop__yarn__node_action_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__node_status_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__master_key_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__node_health_status_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fserver_5fcommon_5fprotos_2eproto__INCLUDED */
