/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fserver_5fresourcemanager_5fservice_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fserver_5fresourcemanager_5fservice_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "yarn_protos.pb-c.h"

typedef struct _Hadoop__Yarn__RefreshQueuesRequestProto Hadoop__Yarn__RefreshQueuesRequestProto;
typedef struct _Hadoop__Yarn__RefreshQueuesResponseProto Hadoop__Yarn__RefreshQueuesResponseProto;
typedef struct _Hadoop__Yarn__RefreshNodesRequestProto Hadoop__Yarn__RefreshNodesRequestProto;
typedef struct _Hadoop__Yarn__RefreshNodesResponseProto Hadoop__Yarn__RefreshNodesResponseProto;
typedef struct _Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto;
typedef struct _Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto;
typedef struct _Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto;
typedef struct _Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto;
typedef struct _Hadoop__Yarn__RefreshAdminAclsRequestProto Hadoop__Yarn__RefreshAdminAclsRequestProto;
typedef struct _Hadoop__Yarn__RefreshAdminAclsResponseProto Hadoop__Yarn__RefreshAdminAclsResponseProto;
typedef struct _Hadoop__Yarn__RefreshServiceAclsRequestProto Hadoop__Yarn__RefreshServiceAclsRequestProto;
typedef struct _Hadoop__Yarn__RefreshServiceAclsResponseProto Hadoop__Yarn__RefreshServiceAclsResponseProto;
typedef struct _Hadoop__Yarn__GetGroupsForUserRequestProto Hadoop__Yarn__GetGroupsForUserRequestProto;
typedef struct _Hadoop__Yarn__GetGroupsForUserResponseProto Hadoop__Yarn__GetGroupsForUserResponseProto;
typedef struct _Hadoop__Yarn__ApplicationStateDataProto Hadoop__Yarn__ApplicationStateDataProto;
typedef struct _Hadoop__Yarn__ApplicationAttemptStateDataProto Hadoop__Yarn__ApplicationAttemptStateDataProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Yarn__RefreshQueuesRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_QUEUES_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_queues_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshQueuesResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_QUEUES_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_queues_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshNodesRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_NODES_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_nodes_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshNodesResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_NODES_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_nodes_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_SUPER_USER_GROUPS_CONFIGURATION_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_USER_TO_GROUPS_MAPPINGS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_USER_TO_GROUPS_MAPPINGS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshAdminAclsRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_ADMIN_ACLS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_admin_acls_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshAdminAclsResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_ADMIN_ACLS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_admin_acls_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshServiceAclsRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_SERVICE_ACLS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_service_acls_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__RefreshServiceAclsResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__REFRESH_SERVICE_ACLS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__refresh_service_acls_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetGroupsForUserRequestProto
{
  ProtobufCMessage base;
  char *user;
};
#define HADOOP__YARN__GET_GROUPS_FOR_USER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_groups_for_user_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__GetGroupsForUserResponseProto
{
  ProtobufCMessage base;
  size_t n_groups;
  char **groups;
};
#define HADOOP__YARN__GET_GROUPS_FOR_USER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_groups_for_user_response_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__ApplicationStateDataProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_submit_time;
  int64_t submit_time;
  Hadoop__Yarn__ApplicationSubmissionContextProto *application_submission_context;
  char *user;
};
#define HADOOP__YARN__APPLICATION_STATE_DATA_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_state_data_proto__descriptor) \
    , 0,0, NULL, NULL }


struct  _Hadoop__Yarn__ApplicationAttemptStateDataProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationAttemptIdProto *attemptid;
  Hadoop__Yarn__ContainerProto *master_container;
  protobuf_c_boolean has_app_attempt_tokens;
  ProtobufCBinaryData app_attempt_tokens;
};
#define HADOOP__YARN__APPLICATION_ATTEMPT_STATE_DATA_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__application_attempt_state_data_proto__descriptor) \
    , NULL, NULL, 0,{0,NULL} }


/* Hadoop__Yarn__RefreshQueuesRequestProto methods */
void   hadoop__yarn__refresh_queues_request_proto__init
                     (Hadoop__Yarn__RefreshQueuesRequestProto         *message);
size_t hadoop__yarn__refresh_queues_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshQueuesRequestProto   *message);
size_t hadoop__yarn__refresh_queues_request_proto__pack
                     (const Hadoop__Yarn__RefreshQueuesRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_queues_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshQueuesRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshQueuesRequestProto *
       hadoop__yarn__refresh_queues_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_queues_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshQueuesRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshQueuesResponseProto methods */
void   hadoop__yarn__refresh_queues_response_proto__init
                     (Hadoop__Yarn__RefreshQueuesResponseProto         *message);
size_t hadoop__yarn__refresh_queues_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshQueuesResponseProto   *message);
size_t hadoop__yarn__refresh_queues_response_proto__pack
                     (const Hadoop__Yarn__RefreshQueuesResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_queues_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshQueuesResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshQueuesResponseProto *
       hadoop__yarn__refresh_queues_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_queues_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshQueuesResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshNodesRequestProto methods */
void   hadoop__yarn__refresh_nodes_request_proto__init
                     (Hadoop__Yarn__RefreshNodesRequestProto         *message);
size_t hadoop__yarn__refresh_nodes_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshNodesRequestProto   *message);
size_t hadoop__yarn__refresh_nodes_request_proto__pack
                     (const Hadoop__Yarn__RefreshNodesRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_nodes_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshNodesRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshNodesRequestProto *
       hadoop__yarn__refresh_nodes_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_nodes_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshNodesRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshNodesResponseProto methods */
void   hadoop__yarn__refresh_nodes_response_proto__init
                     (Hadoop__Yarn__RefreshNodesResponseProto         *message);
size_t hadoop__yarn__refresh_nodes_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshNodesResponseProto   *message);
size_t hadoop__yarn__refresh_nodes_response_proto__pack
                     (const Hadoop__Yarn__RefreshNodesResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_nodes_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshNodesResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshNodesResponseProto *
       hadoop__yarn__refresh_nodes_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_nodes_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshNodesResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto methods */
void   hadoop__yarn__refresh_super_user_groups_configuration_request_proto__init
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto         *message);
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto   *message);
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__pack
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_super_user_groups_configuration_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *
       hadoop__yarn__refresh_super_user_groups_configuration_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_super_user_groups_configuration_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto methods */
void   hadoop__yarn__refresh_super_user_groups_configuration_response_proto__init
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto         *message);
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto   *message);
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__pack
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_super_user_groups_configuration_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *
       hadoop__yarn__refresh_super_user_groups_configuration_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_super_user_groups_configuration_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto methods */
void   hadoop__yarn__refresh_user_to_groups_mappings_request_proto__init
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto         *message);
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto   *message);
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__pack
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_user_to_groups_mappings_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *
       hadoop__yarn__refresh_user_to_groups_mappings_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_user_to_groups_mappings_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto methods */
void   hadoop__yarn__refresh_user_to_groups_mappings_response_proto__init
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto         *message);
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto   *message);
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__pack
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_user_to_groups_mappings_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *
       hadoop__yarn__refresh_user_to_groups_mappings_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_user_to_groups_mappings_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshAdminAclsRequestProto methods */
void   hadoop__yarn__refresh_admin_acls_request_proto__init
                     (Hadoop__Yarn__RefreshAdminAclsRequestProto         *message);
size_t hadoop__yarn__refresh_admin_acls_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto   *message);
size_t hadoop__yarn__refresh_admin_acls_request_proto__pack
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_admin_acls_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshAdminAclsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshAdminAclsRequestProto *
       hadoop__yarn__refresh_admin_acls_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_admin_acls_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshAdminAclsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshAdminAclsResponseProto methods */
void   hadoop__yarn__refresh_admin_acls_response_proto__init
                     (Hadoop__Yarn__RefreshAdminAclsResponseProto         *message);
size_t hadoop__yarn__refresh_admin_acls_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto   *message);
size_t hadoop__yarn__refresh_admin_acls_response_proto__pack
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_admin_acls_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshAdminAclsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshAdminAclsResponseProto *
       hadoop__yarn__refresh_admin_acls_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_admin_acls_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshAdminAclsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshServiceAclsRequestProto methods */
void   hadoop__yarn__refresh_service_acls_request_proto__init
                     (Hadoop__Yarn__RefreshServiceAclsRequestProto         *message);
size_t hadoop__yarn__refresh_service_acls_request_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto   *message);
size_t hadoop__yarn__refresh_service_acls_request_proto__pack
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_service_acls_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshServiceAclsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshServiceAclsRequestProto *
       hadoop__yarn__refresh_service_acls_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_service_acls_request_proto__free_unpacked
                     (Hadoop__Yarn__RefreshServiceAclsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RefreshServiceAclsResponseProto methods */
void   hadoop__yarn__refresh_service_acls_response_proto__init
                     (Hadoop__Yarn__RefreshServiceAclsResponseProto         *message);
size_t hadoop__yarn__refresh_service_acls_response_proto__get_packed_size
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto   *message);
size_t hadoop__yarn__refresh_service_acls_response_proto__pack
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__refresh_service_acls_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RefreshServiceAclsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RefreshServiceAclsResponseProto *
       hadoop__yarn__refresh_service_acls_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__refresh_service_acls_response_proto__free_unpacked
                     (Hadoop__Yarn__RefreshServiceAclsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetGroupsForUserRequestProto methods */
void   hadoop__yarn__get_groups_for_user_request_proto__init
                     (Hadoop__Yarn__GetGroupsForUserRequestProto         *message);
size_t hadoop__yarn__get_groups_for_user_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto   *message);
size_t hadoop__yarn__get_groups_for_user_request_proto__pack
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_groups_for_user_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetGroupsForUserRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetGroupsForUserRequestProto *
       hadoop__yarn__get_groups_for_user_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_groups_for_user_request_proto__free_unpacked
                     (Hadoop__Yarn__GetGroupsForUserRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetGroupsForUserResponseProto methods */
void   hadoop__yarn__get_groups_for_user_response_proto__init
                     (Hadoop__Yarn__GetGroupsForUserResponseProto         *message);
size_t hadoop__yarn__get_groups_for_user_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto   *message);
size_t hadoop__yarn__get_groups_for_user_response_proto__pack
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_groups_for_user_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetGroupsForUserResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetGroupsForUserResponseProto *
       hadoop__yarn__get_groups_for_user_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_groups_for_user_response_proto__free_unpacked
                     (Hadoop__Yarn__GetGroupsForUserResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationStateDataProto methods */
void   hadoop__yarn__application_state_data_proto__init
                     (Hadoop__Yarn__ApplicationStateDataProto         *message);
size_t hadoop__yarn__application_state_data_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationStateDataProto   *message);
size_t hadoop__yarn__application_state_data_proto__pack
                     (const Hadoop__Yarn__ApplicationStateDataProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_state_data_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationStateDataProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationStateDataProto *
       hadoop__yarn__application_state_data_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_state_data_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationStateDataProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ApplicationAttemptStateDataProto methods */
void   hadoop__yarn__application_attempt_state_data_proto__init
                     (Hadoop__Yarn__ApplicationAttemptStateDataProto         *message);
size_t hadoop__yarn__application_attempt_state_data_proto__get_packed_size
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto   *message);
size_t hadoop__yarn__application_attempt_state_data_proto__pack
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__application_attempt_state_data_proto__pack_to_buffer
                     (const Hadoop__Yarn__ApplicationAttemptStateDataProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ApplicationAttemptStateDataProto *
       hadoop__yarn__application_attempt_state_data_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__application_attempt_state_data_proto__free_unpacked
                     (Hadoop__Yarn__ApplicationAttemptStateDataProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Yarn__RefreshQueuesRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshQueuesRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshQueuesResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshQueuesResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshNodesRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshNodesRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshNodesResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshNodesResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshSuperUserGroupsConfigurationResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshUserToGroupsMappingsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshUserToGroupsMappingsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshAdminAclsRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshAdminAclsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshAdminAclsResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshAdminAclsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshServiceAclsRequestProto_Closure)
                 (const Hadoop__Yarn__RefreshServiceAclsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RefreshServiceAclsResponseProto_Closure)
                 (const Hadoop__Yarn__RefreshServiceAclsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetGroupsForUserRequestProto_Closure)
                 (const Hadoop__Yarn__GetGroupsForUserRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetGroupsForUserResponseProto_Closure)
                 (const Hadoop__Yarn__GetGroupsForUserResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationStateDataProto_Closure)
                 (const Hadoop__Yarn__ApplicationStateDataProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ApplicationAttemptStateDataProto_Closure)
                 (const Hadoop__Yarn__ApplicationAttemptStateDataProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_queues_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_queues_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_nodes_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_nodes_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_super_user_groups_configuration_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_super_user_groups_configuration_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_user_to_groups_mappings_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_user_to_groups_mappings_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_admin_acls_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_admin_acls_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_service_acls_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__refresh_service_acls_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_groups_for_user_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_groups_for_user_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_state_data_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__application_attempt_state_data_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fserver_5fresourcemanager_5fservice_5fprotos_2eproto__INCLUDED */
