/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_yarn_5fservice_5fprotos_2eproto__INCLUDED
#define PROTOBUF_C_yarn_5fservice_5fprotos_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "Security.pb-c.h"
#include "yarn_protos.pb-c.h"

typedef struct _Hadoop__Yarn__RegisterApplicationMasterRequestProto Hadoop__Yarn__RegisterApplicationMasterRequestProto;
typedef struct _Hadoop__Yarn__RegisterApplicationMasterResponseProto Hadoop__Yarn__RegisterApplicationMasterResponseProto;
typedef struct _Hadoop__Yarn__FinishApplicationMasterRequestProto Hadoop__Yarn__FinishApplicationMasterRequestProto;
typedef struct _Hadoop__Yarn__FinishApplicationMasterResponseProto Hadoop__Yarn__FinishApplicationMasterResponseProto;
typedef struct _Hadoop__Yarn__AllocateRequestProto Hadoop__Yarn__AllocateRequestProto;
typedef struct _Hadoop__Yarn__NMTokenProto Hadoop__Yarn__NMTokenProto;
typedef struct _Hadoop__Yarn__AllocateResponseProto Hadoop__Yarn__AllocateResponseProto;
typedef struct _Hadoop__Yarn__GetNewApplicationRequestProto Hadoop__Yarn__GetNewApplicationRequestProto;
typedef struct _Hadoop__Yarn__GetNewApplicationResponseProto Hadoop__Yarn__GetNewApplicationResponseProto;
typedef struct _Hadoop__Yarn__GetApplicationReportRequestProto Hadoop__Yarn__GetApplicationReportRequestProto;
typedef struct _Hadoop__Yarn__GetApplicationReportResponseProto Hadoop__Yarn__GetApplicationReportResponseProto;
typedef struct _Hadoop__Yarn__SubmitApplicationRequestProto Hadoop__Yarn__SubmitApplicationRequestProto;
typedef struct _Hadoop__Yarn__SubmitApplicationResponseProto Hadoop__Yarn__SubmitApplicationResponseProto;
typedef struct _Hadoop__Yarn__KillApplicationRequestProto Hadoop__Yarn__KillApplicationRequestProto;
typedef struct _Hadoop__Yarn__KillApplicationResponseProto Hadoop__Yarn__KillApplicationResponseProto;
typedef struct _Hadoop__Yarn__GetClusterMetricsRequestProto Hadoop__Yarn__GetClusterMetricsRequestProto;
typedef struct _Hadoop__Yarn__GetClusterMetricsResponseProto Hadoop__Yarn__GetClusterMetricsResponseProto;
typedef struct _Hadoop__Yarn__GetApplicationsRequestProto Hadoop__Yarn__GetApplicationsRequestProto;
typedef struct _Hadoop__Yarn__GetApplicationsResponseProto Hadoop__Yarn__GetApplicationsResponseProto;
typedef struct _Hadoop__Yarn__GetClusterNodesRequestProto Hadoop__Yarn__GetClusterNodesRequestProto;
typedef struct _Hadoop__Yarn__GetClusterNodesResponseProto Hadoop__Yarn__GetClusterNodesResponseProto;
typedef struct _Hadoop__Yarn__GetQueueInfoRequestProto Hadoop__Yarn__GetQueueInfoRequestProto;
typedef struct _Hadoop__Yarn__GetQueueInfoResponseProto Hadoop__Yarn__GetQueueInfoResponseProto;
typedef struct _Hadoop__Yarn__GetQueueUserAclsInfoRequestProto Hadoop__Yarn__GetQueueUserAclsInfoRequestProto;
typedef struct _Hadoop__Yarn__GetQueueUserAclsInfoResponseProto Hadoop__Yarn__GetQueueUserAclsInfoResponseProto;
typedef struct _Hadoop__Yarn__StartContainerRequestProto Hadoop__Yarn__StartContainerRequestProto;
typedef struct _Hadoop__Yarn__StartContainerResponseProto Hadoop__Yarn__StartContainerResponseProto;
typedef struct _Hadoop__Yarn__StopContainerRequestProto Hadoop__Yarn__StopContainerRequestProto;
typedef struct _Hadoop__Yarn__StopContainerResponseProto Hadoop__Yarn__StopContainerResponseProto;
typedef struct _Hadoop__Yarn__GetContainerStatusRequestProto Hadoop__Yarn__GetContainerStatusRequestProto;
typedef struct _Hadoop__Yarn__GetContainerStatusResponseProto Hadoop__Yarn__GetContainerStatusResponseProto;
typedef struct _Hadoop__Yarn__StartContainersRequestProto Hadoop__Yarn__StartContainersRequestProto;
typedef struct _Hadoop__Yarn__ContainerExceptionMapProto Hadoop__Yarn__ContainerExceptionMapProto;
typedef struct _Hadoop__Yarn__StartContainersResponseProto Hadoop__Yarn__StartContainersResponseProto;
typedef struct _Hadoop__Yarn__StopContainersRequestProto Hadoop__Yarn__StopContainersRequestProto;
typedef struct _Hadoop__Yarn__StopContainersResponseProto Hadoop__Yarn__StopContainersResponseProto;
typedef struct _Hadoop__Yarn__GetContainerStatusesRequestProto Hadoop__Yarn__GetContainerStatusesRequestProto;
typedef struct _Hadoop__Yarn__GetContainerStatusesResponseProto Hadoop__Yarn__GetContainerStatusesResponseProto;


/* --- enums --- */


/* --- messages --- */

struct  _Hadoop__Yarn__RegisterApplicationMasterRequestProto
{
  ProtobufCMessage base;
  char *host;
  protobuf_c_boolean has_rpc_port;
  int32_t rpc_port;
  char *tracking_url;
};
#define HADOOP__YARN__REGISTER_APPLICATION_MASTER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__register_application_master_request_proto__descriptor) \
    , NULL, 0,0, NULL }


struct  _Hadoop__Yarn__RegisterApplicationMasterResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ResourceProto *maximumcapability;
  protobuf_c_boolean has_client_to_am_token_master_key;
  ProtobufCBinaryData client_to_am_token_master_key;
  size_t n_application_acls;
  Hadoop__Yarn__ApplicationACLMapProto **application_acls;
};
#define HADOOP__YARN__REGISTER_APPLICATION_MASTER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__register_application_master_response_proto__descriptor) \
    , NULL, 0,{0,NULL}, 0,NULL }


struct  _Hadoop__Yarn__FinishApplicationMasterRequestProto
{
  ProtobufCMessage base;
  char *diagnostics;
  char *tracking_url;
  protobuf_c_boolean has_final_application_status;
  Hadoop__Yarn__FinalApplicationStatusProto final_application_status;
};
#define HADOOP__YARN__FINISH_APPLICATION_MASTER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__finish_application_master_request_proto__descriptor) \
    , NULL, NULL, 0,0 }


struct  _Hadoop__Yarn__FinishApplicationMasterResponseProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_isunregistered;
  protobuf_c_boolean isunregistered;
};
#define HADOOP__YARN__FINISH_APPLICATION_MASTER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__finish_application_master_response_proto__descriptor) \
    , 0,0 }


struct  _Hadoop__Yarn__AllocateRequestProto
{
  ProtobufCMessage base;
  size_t n_ask;
  Hadoop__Yarn__ResourceRequestProto **ask;
  size_t n_release;
  Hadoop__Yarn__ContainerIdProto **release;
  Hadoop__Yarn__ResourceBlacklistRequestProto *blacklist_request;
  protobuf_c_boolean has_response_id;
  int32_t response_id;
  protobuf_c_boolean has_progress;
  float progress;
};
#define HADOOP__YARN__ALLOCATE_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__allocate_request_proto__descriptor) \
    , 0,NULL, 0,NULL, NULL, 0,0, 0,0 }


struct  _Hadoop__Yarn__NMTokenProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__NodeIdProto *nodeid;
  Hadoop__Common__TokenProto *token;
};
#define HADOOP__YARN__NMTOKEN_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__nmtoken_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__AllocateResponseProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_a_m_command;
  Hadoop__Yarn__AMCommandProto a_m_command;
  protobuf_c_boolean has_response_id;
  int32_t response_id;
  size_t n_allocated_containers;
  Hadoop__Yarn__ContainerProto **allocated_containers;
  size_t n_completed_container_statuses;
  Hadoop__Yarn__ContainerStatusProto **completed_container_statuses;
  Hadoop__Yarn__ResourceProto *limit;
  size_t n_updated_nodes;
  Hadoop__Yarn__NodeReportProto **updated_nodes;
  protobuf_c_boolean has_num_cluster_nodes;
  int32_t num_cluster_nodes;
  Hadoop__Yarn__PreemptionMessageProto *preempt;
  size_t n_nm_tokens;
  Hadoop__Yarn__NMTokenProto **nm_tokens;
};
#define HADOOP__YARN__ALLOCATE_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__allocate_response_proto__descriptor) \
    , 0,0, 0,0, 0,NULL, 0,NULL, NULL, 0,NULL, 0,0, NULL, 0,NULL }


struct  _Hadoop__Yarn__GetNewApplicationRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__GET_NEW_APPLICATION_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_new_application_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetNewApplicationResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *application_id;
  Hadoop__Yarn__ResourceProto *maximumcapability;
};
#define HADOOP__YARN__GET_NEW_APPLICATION_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_new_application_response_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__GetApplicationReportRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *application_id;
};
#define HADOOP__YARN__GET_APPLICATION_REPORT_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_application_report_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__GetApplicationReportResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationReportProto *application_report;
};
#define HADOOP__YARN__GET_APPLICATION_REPORT_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_application_report_response_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__SubmitApplicationRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationSubmissionContextProto *application_submission_context;
};
#define HADOOP__YARN__SUBMIT_APPLICATION_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__submit_application_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__SubmitApplicationResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__SUBMIT_APPLICATION_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__submit_application_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__KillApplicationRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ApplicationIdProto *application_id;
};
#define HADOOP__YARN__KILL_APPLICATION_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__kill_application_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__KillApplicationResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__KILL_APPLICATION_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__kill_application_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetClusterMetricsRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__GET_CLUSTER_METRICS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_cluster_metrics_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetClusterMetricsResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__YarnClusterMetricsProto *cluster_metrics;
};
#define HADOOP__YARN__GET_CLUSTER_METRICS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_cluster_metrics_response_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__GetApplicationsRequestProto
{
  ProtobufCMessage base;
  size_t n_application_types;
  char **application_types;
  size_t n_application_states;
  Hadoop__Yarn__YarnApplicationStateProto *application_states;
};
#define HADOOP__YARN__GET_APPLICATIONS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_applications_request_proto__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__GetApplicationsResponseProto
{
  ProtobufCMessage base;
  size_t n_applications;
  Hadoop__Yarn__ApplicationReportProto **applications;
};
#define HADOOP__YARN__GET_APPLICATIONS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_applications_response_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__GetClusterNodesRequestProto
{
  ProtobufCMessage base;
  size_t n_nodestates;
  Hadoop__Yarn__NodeStateProto *nodestates;
};
#define HADOOP__YARN__GET_CLUSTER_NODES_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_cluster_nodes_request_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__GetClusterNodesResponseProto
{
  ProtobufCMessage base;
  size_t n_nodereports;
  Hadoop__Yarn__NodeReportProto **nodereports;
};
#define HADOOP__YARN__GET_CLUSTER_NODES_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_cluster_nodes_response_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__GetQueueInfoRequestProto
{
  ProtobufCMessage base;
  char *queuename;
  protobuf_c_boolean has_includeapplications;
  protobuf_c_boolean includeapplications;
  protobuf_c_boolean has_includechildqueues;
  protobuf_c_boolean includechildqueues;
  protobuf_c_boolean has_recursive;
  protobuf_c_boolean recursive;
};
#define HADOOP__YARN__GET_QUEUE_INFO_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_queue_info_request_proto__descriptor) \
    , NULL, 0,0, 0,0, 0,0 }


struct  _Hadoop__Yarn__GetQueueInfoResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__QueueInfoProto *queueinfo;
};
#define HADOOP__YARN__GET_QUEUE_INFO_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_queue_info_response_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__GetQueueUserAclsInfoRequestProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__GET_QUEUE_USER_ACLS_INFO_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_queue_user_acls_info_request_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetQueueUserAclsInfoResponseProto
{
  ProtobufCMessage base;
  size_t n_queueuseracls;
  Hadoop__Yarn__QueueUserACLInfoProto **queueuseracls;
};
#define HADOOP__YARN__GET_QUEUE_USER_ACLS_INFO_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_queue_user_acls_info_response_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__StartContainerRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerLaunchContextProto *container_launch_context;
  Hadoop__Common__TokenProto *container_token;
};
#define HADOOP__YARN__START_CONTAINER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__start_container_request_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__StartContainerResponseProto
{
  ProtobufCMessage base;
  size_t n_services_meta_data;
  Hadoop__Yarn__StringBytesMapProto **services_meta_data;
};
#define HADOOP__YARN__START_CONTAINER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__start_container_response_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__StopContainerRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *container_id;
};
#define HADOOP__YARN__STOP_CONTAINER_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__stop_container_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__StopContainerResponseProto
{
  ProtobufCMessage base;
};
#define HADOOP__YARN__STOP_CONTAINER_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__stop_container_response_proto__descriptor) \
     }


struct  _Hadoop__Yarn__GetContainerStatusRequestProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *container_id;
};
#define HADOOP__YARN__GET_CONTAINER_STATUS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_container_status_request_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__GetContainerStatusResponseProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerStatusProto *status;
};
#define HADOOP__YARN__GET_CONTAINER_STATUS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_container_status_response_proto__descriptor) \
    , NULL }


struct  _Hadoop__Yarn__StartContainersRequestProto
{
  ProtobufCMessage base;
  size_t n_start_container_request;
  Hadoop__Yarn__StartContainerRequestProto **start_container_request;
};
#define HADOOP__YARN__START_CONTAINERS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__start_containers_request_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__ContainerExceptionMapProto
{
  ProtobufCMessage base;
  Hadoop__Yarn__ContainerIdProto *container_id;
  Hadoop__Yarn__SerializedExceptionProto *exception;
};
#define HADOOP__YARN__CONTAINER_EXCEPTION_MAP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__container_exception_map_proto__descriptor) \
    , NULL, NULL }


struct  _Hadoop__Yarn__StartContainersResponseProto
{
  ProtobufCMessage base;
  size_t n_services_meta_data;
  Hadoop__Yarn__StringBytesMapProto **services_meta_data;
  size_t n_succeeded_requests;
  Hadoop__Yarn__ContainerIdProto **succeeded_requests;
  size_t n_failed_requests;
  Hadoop__Yarn__ContainerExceptionMapProto **failed_requests;
};
#define HADOOP__YARN__START_CONTAINERS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__start_containers_response_proto__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__StopContainersRequestProto
{
  ProtobufCMessage base;
  size_t n_container_id;
  Hadoop__Yarn__ContainerIdProto **container_id;
};
#define HADOOP__YARN__STOP_CONTAINERS_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__stop_containers_request_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__StopContainersResponseProto
{
  ProtobufCMessage base;
  size_t n_succeeded_requests;
  Hadoop__Yarn__ContainerIdProto **succeeded_requests;
  size_t n_failed_requests;
  Hadoop__Yarn__ContainerExceptionMapProto **failed_requests;
};
#define HADOOP__YARN__STOP_CONTAINERS_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__stop_containers_response_proto__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Hadoop__Yarn__GetContainerStatusesRequestProto
{
  ProtobufCMessage base;
  size_t n_container_id;
  Hadoop__Yarn__ContainerIdProto **container_id;
};
#define HADOOP__YARN__GET_CONTAINER_STATUSES_REQUEST_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_container_statuses_request_proto__descriptor) \
    , 0,NULL }


struct  _Hadoop__Yarn__GetContainerStatusesResponseProto
{
  ProtobufCMessage base;
  size_t n_status;
  Hadoop__Yarn__ContainerStatusProto **status;
  size_t n_failed_requests;
  Hadoop__Yarn__ContainerExceptionMapProto **failed_requests;
};
#define HADOOP__YARN__GET_CONTAINER_STATUSES_RESPONSE_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hadoop__yarn__get_container_statuses_response_proto__descriptor) \
    , 0,NULL, 0,NULL }


/* Hadoop__Yarn__RegisterApplicationMasterRequestProto methods */
void   hadoop__yarn__register_application_master_request_proto__init
                     (Hadoop__Yarn__RegisterApplicationMasterRequestProto         *message);
size_t hadoop__yarn__register_application_master_request_proto__get_packed_size
                     (const Hadoop__Yarn__RegisterApplicationMasterRequestProto   *message);
size_t hadoop__yarn__register_application_master_request_proto__pack
                     (const Hadoop__Yarn__RegisterApplicationMasterRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__register_application_master_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__RegisterApplicationMasterRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RegisterApplicationMasterRequestProto *
       hadoop__yarn__register_application_master_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__register_application_master_request_proto__free_unpacked
                     (Hadoop__Yarn__RegisterApplicationMasterRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__RegisterApplicationMasterResponseProto methods */
void   hadoop__yarn__register_application_master_response_proto__init
                     (Hadoop__Yarn__RegisterApplicationMasterResponseProto         *message);
size_t hadoop__yarn__register_application_master_response_proto__get_packed_size
                     (const Hadoop__Yarn__RegisterApplicationMasterResponseProto   *message);
size_t hadoop__yarn__register_application_master_response_proto__pack
                     (const Hadoop__Yarn__RegisterApplicationMasterResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__register_application_master_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__RegisterApplicationMasterResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__RegisterApplicationMasterResponseProto *
       hadoop__yarn__register_application_master_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__register_application_master_response_proto__free_unpacked
                     (Hadoop__Yarn__RegisterApplicationMasterResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__FinishApplicationMasterRequestProto methods */
void   hadoop__yarn__finish_application_master_request_proto__init
                     (Hadoop__Yarn__FinishApplicationMasterRequestProto         *message);
size_t hadoop__yarn__finish_application_master_request_proto__get_packed_size
                     (const Hadoop__Yarn__FinishApplicationMasterRequestProto   *message);
size_t hadoop__yarn__finish_application_master_request_proto__pack
                     (const Hadoop__Yarn__FinishApplicationMasterRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__finish_application_master_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__FinishApplicationMasterRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__FinishApplicationMasterRequestProto *
       hadoop__yarn__finish_application_master_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__finish_application_master_request_proto__free_unpacked
                     (Hadoop__Yarn__FinishApplicationMasterRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__FinishApplicationMasterResponseProto methods */
void   hadoop__yarn__finish_application_master_response_proto__init
                     (Hadoop__Yarn__FinishApplicationMasterResponseProto         *message);
size_t hadoop__yarn__finish_application_master_response_proto__get_packed_size
                     (const Hadoop__Yarn__FinishApplicationMasterResponseProto   *message);
size_t hadoop__yarn__finish_application_master_response_proto__pack
                     (const Hadoop__Yarn__FinishApplicationMasterResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__finish_application_master_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__FinishApplicationMasterResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__FinishApplicationMasterResponseProto *
       hadoop__yarn__finish_application_master_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__finish_application_master_response_proto__free_unpacked
                     (Hadoop__Yarn__FinishApplicationMasterResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__AllocateRequestProto methods */
void   hadoop__yarn__allocate_request_proto__init
                     (Hadoop__Yarn__AllocateRequestProto         *message);
size_t hadoop__yarn__allocate_request_proto__get_packed_size
                     (const Hadoop__Yarn__AllocateRequestProto   *message);
size_t hadoop__yarn__allocate_request_proto__pack
                     (const Hadoop__Yarn__AllocateRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__allocate_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__AllocateRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__AllocateRequestProto *
       hadoop__yarn__allocate_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__allocate_request_proto__free_unpacked
                     (Hadoop__Yarn__AllocateRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__NMTokenProto methods */
void   hadoop__yarn__nmtoken_proto__init
                     (Hadoop__Yarn__NMTokenProto         *message);
size_t hadoop__yarn__nmtoken_proto__get_packed_size
                     (const Hadoop__Yarn__NMTokenProto   *message);
size_t hadoop__yarn__nmtoken_proto__pack
                     (const Hadoop__Yarn__NMTokenProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__nmtoken_proto__pack_to_buffer
                     (const Hadoop__Yarn__NMTokenProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__NMTokenProto *
       hadoop__yarn__nmtoken_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__nmtoken_proto__free_unpacked
                     (Hadoop__Yarn__NMTokenProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__AllocateResponseProto methods */
void   hadoop__yarn__allocate_response_proto__init
                     (Hadoop__Yarn__AllocateResponseProto         *message);
size_t hadoop__yarn__allocate_response_proto__get_packed_size
                     (const Hadoop__Yarn__AllocateResponseProto   *message);
size_t hadoop__yarn__allocate_response_proto__pack
                     (const Hadoop__Yarn__AllocateResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__allocate_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__AllocateResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__AllocateResponseProto *
       hadoop__yarn__allocate_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__allocate_response_proto__free_unpacked
                     (Hadoop__Yarn__AllocateResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetNewApplicationRequestProto methods */
void   hadoop__yarn__get_new_application_request_proto__init
                     (Hadoop__Yarn__GetNewApplicationRequestProto         *message);
size_t hadoop__yarn__get_new_application_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetNewApplicationRequestProto   *message);
size_t hadoop__yarn__get_new_application_request_proto__pack
                     (const Hadoop__Yarn__GetNewApplicationRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_new_application_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetNewApplicationRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetNewApplicationRequestProto *
       hadoop__yarn__get_new_application_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_new_application_request_proto__free_unpacked
                     (Hadoop__Yarn__GetNewApplicationRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetNewApplicationResponseProto methods */
void   hadoop__yarn__get_new_application_response_proto__init
                     (Hadoop__Yarn__GetNewApplicationResponseProto         *message);
size_t hadoop__yarn__get_new_application_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetNewApplicationResponseProto   *message);
size_t hadoop__yarn__get_new_application_response_proto__pack
                     (const Hadoop__Yarn__GetNewApplicationResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_new_application_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetNewApplicationResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetNewApplicationResponseProto *
       hadoop__yarn__get_new_application_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_new_application_response_proto__free_unpacked
                     (Hadoop__Yarn__GetNewApplicationResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetApplicationReportRequestProto methods */
void   hadoop__yarn__get_application_report_request_proto__init
                     (Hadoop__Yarn__GetApplicationReportRequestProto         *message);
size_t hadoop__yarn__get_application_report_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetApplicationReportRequestProto   *message);
size_t hadoop__yarn__get_application_report_request_proto__pack
                     (const Hadoop__Yarn__GetApplicationReportRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_application_report_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetApplicationReportRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetApplicationReportRequestProto *
       hadoop__yarn__get_application_report_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_application_report_request_proto__free_unpacked
                     (Hadoop__Yarn__GetApplicationReportRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetApplicationReportResponseProto methods */
void   hadoop__yarn__get_application_report_response_proto__init
                     (Hadoop__Yarn__GetApplicationReportResponseProto         *message);
size_t hadoop__yarn__get_application_report_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetApplicationReportResponseProto   *message);
size_t hadoop__yarn__get_application_report_response_proto__pack
                     (const Hadoop__Yarn__GetApplicationReportResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_application_report_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetApplicationReportResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetApplicationReportResponseProto *
       hadoop__yarn__get_application_report_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_application_report_response_proto__free_unpacked
                     (Hadoop__Yarn__GetApplicationReportResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__SubmitApplicationRequestProto methods */
void   hadoop__yarn__submit_application_request_proto__init
                     (Hadoop__Yarn__SubmitApplicationRequestProto         *message);
size_t hadoop__yarn__submit_application_request_proto__get_packed_size
                     (const Hadoop__Yarn__SubmitApplicationRequestProto   *message);
size_t hadoop__yarn__submit_application_request_proto__pack
                     (const Hadoop__Yarn__SubmitApplicationRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__submit_application_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__SubmitApplicationRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__SubmitApplicationRequestProto *
       hadoop__yarn__submit_application_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__submit_application_request_proto__free_unpacked
                     (Hadoop__Yarn__SubmitApplicationRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__SubmitApplicationResponseProto methods */
void   hadoop__yarn__submit_application_response_proto__init
                     (Hadoop__Yarn__SubmitApplicationResponseProto         *message);
size_t hadoop__yarn__submit_application_response_proto__get_packed_size
                     (const Hadoop__Yarn__SubmitApplicationResponseProto   *message);
size_t hadoop__yarn__submit_application_response_proto__pack
                     (const Hadoop__Yarn__SubmitApplicationResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__submit_application_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__SubmitApplicationResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__SubmitApplicationResponseProto *
       hadoop__yarn__submit_application_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__submit_application_response_proto__free_unpacked
                     (Hadoop__Yarn__SubmitApplicationResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__KillApplicationRequestProto methods */
void   hadoop__yarn__kill_application_request_proto__init
                     (Hadoop__Yarn__KillApplicationRequestProto         *message);
size_t hadoop__yarn__kill_application_request_proto__get_packed_size
                     (const Hadoop__Yarn__KillApplicationRequestProto   *message);
size_t hadoop__yarn__kill_application_request_proto__pack
                     (const Hadoop__Yarn__KillApplicationRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__kill_application_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__KillApplicationRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__KillApplicationRequestProto *
       hadoop__yarn__kill_application_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__kill_application_request_proto__free_unpacked
                     (Hadoop__Yarn__KillApplicationRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__KillApplicationResponseProto methods */
void   hadoop__yarn__kill_application_response_proto__init
                     (Hadoop__Yarn__KillApplicationResponseProto         *message);
size_t hadoop__yarn__kill_application_response_proto__get_packed_size
                     (const Hadoop__Yarn__KillApplicationResponseProto   *message);
size_t hadoop__yarn__kill_application_response_proto__pack
                     (const Hadoop__Yarn__KillApplicationResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__kill_application_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__KillApplicationResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__KillApplicationResponseProto *
       hadoop__yarn__kill_application_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__kill_application_response_proto__free_unpacked
                     (Hadoop__Yarn__KillApplicationResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetClusterMetricsRequestProto methods */
void   hadoop__yarn__get_cluster_metrics_request_proto__init
                     (Hadoop__Yarn__GetClusterMetricsRequestProto         *message);
size_t hadoop__yarn__get_cluster_metrics_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetClusterMetricsRequestProto   *message);
size_t hadoop__yarn__get_cluster_metrics_request_proto__pack
                     (const Hadoop__Yarn__GetClusterMetricsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_cluster_metrics_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetClusterMetricsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetClusterMetricsRequestProto *
       hadoop__yarn__get_cluster_metrics_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_cluster_metrics_request_proto__free_unpacked
                     (Hadoop__Yarn__GetClusterMetricsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetClusterMetricsResponseProto methods */
void   hadoop__yarn__get_cluster_metrics_response_proto__init
                     (Hadoop__Yarn__GetClusterMetricsResponseProto         *message);
size_t hadoop__yarn__get_cluster_metrics_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetClusterMetricsResponseProto   *message);
size_t hadoop__yarn__get_cluster_metrics_response_proto__pack
                     (const Hadoop__Yarn__GetClusterMetricsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_cluster_metrics_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetClusterMetricsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetClusterMetricsResponseProto *
       hadoop__yarn__get_cluster_metrics_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_cluster_metrics_response_proto__free_unpacked
                     (Hadoop__Yarn__GetClusterMetricsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetApplicationsRequestProto methods */
void   hadoop__yarn__get_applications_request_proto__init
                     (Hadoop__Yarn__GetApplicationsRequestProto         *message);
size_t hadoop__yarn__get_applications_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetApplicationsRequestProto   *message);
size_t hadoop__yarn__get_applications_request_proto__pack
                     (const Hadoop__Yarn__GetApplicationsRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_applications_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetApplicationsRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetApplicationsRequestProto *
       hadoop__yarn__get_applications_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_applications_request_proto__free_unpacked
                     (Hadoop__Yarn__GetApplicationsRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetApplicationsResponseProto methods */
void   hadoop__yarn__get_applications_response_proto__init
                     (Hadoop__Yarn__GetApplicationsResponseProto         *message);
size_t hadoop__yarn__get_applications_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetApplicationsResponseProto   *message);
size_t hadoop__yarn__get_applications_response_proto__pack
                     (const Hadoop__Yarn__GetApplicationsResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_applications_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetApplicationsResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetApplicationsResponseProto *
       hadoop__yarn__get_applications_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_applications_response_proto__free_unpacked
                     (Hadoop__Yarn__GetApplicationsResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetClusterNodesRequestProto methods */
void   hadoop__yarn__get_cluster_nodes_request_proto__init
                     (Hadoop__Yarn__GetClusterNodesRequestProto         *message);
size_t hadoop__yarn__get_cluster_nodes_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetClusterNodesRequestProto   *message);
size_t hadoop__yarn__get_cluster_nodes_request_proto__pack
                     (const Hadoop__Yarn__GetClusterNodesRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_cluster_nodes_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetClusterNodesRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetClusterNodesRequestProto *
       hadoop__yarn__get_cluster_nodes_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_cluster_nodes_request_proto__free_unpacked
                     (Hadoop__Yarn__GetClusterNodesRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetClusterNodesResponseProto methods */
void   hadoop__yarn__get_cluster_nodes_response_proto__init
                     (Hadoop__Yarn__GetClusterNodesResponseProto         *message);
size_t hadoop__yarn__get_cluster_nodes_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetClusterNodesResponseProto   *message);
size_t hadoop__yarn__get_cluster_nodes_response_proto__pack
                     (const Hadoop__Yarn__GetClusterNodesResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_cluster_nodes_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetClusterNodesResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetClusterNodesResponseProto *
       hadoop__yarn__get_cluster_nodes_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_cluster_nodes_response_proto__free_unpacked
                     (Hadoop__Yarn__GetClusterNodesResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetQueueInfoRequestProto methods */
void   hadoop__yarn__get_queue_info_request_proto__init
                     (Hadoop__Yarn__GetQueueInfoRequestProto         *message);
size_t hadoop__yarn__get_queue_info_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetQueueInfoRequestProto   *message);
size_t hadoop__yarn__get_queue_info_request_proto__pack
                     (const Hadoop__Yarn__GetQueueInfoRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_queue_info_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetQueueInfoRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetQueueInfoRequestProto *
       hadoop__yarn__get_queue_info_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_queue_info_request_proto__free_unpacked
                     (Hadoop__Yarn__GetQueueInfoRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetQueueInfoResponseProto methods */
void   hadoop__yarn__get_queue_info_response_proto__init
                     (Hadoop__Yarn__GetQueueInfoResponseProto         *message);
size_t hadoop__yarn__get_queue_info_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetQueueInfoResponseProto   *message);
size_t hadoop__yarn__get_queue_info_response_proto__pack
                     (const Hadoop__Yarn__GetQueueInfoResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_queue_info_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetQueueInfoResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetQueueInfoResponseProto *
       hadoop__yarn__get_queue_info_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_queue_info_response_proto__free_unpacked
                     (Hadoop__Yarn__GetQueueInfoResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetQueueUserAclsInfoRequestProto methods */
void   hadoop__yarn__get_queue_user_acls_info_request_proto__init
                     (Hadoop__Yarn__GetQueueUserAclsInfoRequestProto         *message);
size_t hadoop__yarn__get_queue_user_acls_info_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetQueueUserAclsInfoRequestProto   *message);
size_t hadoop__yarn__get_queue_user_acls_info_request_proto__pack
                     (const Hadoop__Yarn__GetQueueUserAclsInfoRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_queue_user_acls_info_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetQueueUserAclsInfoRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetQueueUserAclsInfoRequestProto *
       hadoop__yarn__get_queue_user_acls_info_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_queue_user_acls_info_request_proto__free_unpacked
                     (Hadoop__Yarn__GetQueueUserAclsInfoRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetQueueUserAclsInfoResponseProto methods */
void   hadoop__yarn__get_queue_user_acls_info_response_proto__init
                     (Hadoop__Yarn__GetQueueUserAclsInfoResponseProto         *message);
size_t hadoop__yarn__get_queue_user_acls_info_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetQueueUserAclsInfoResponseProto   *message);
size_t hadoop__yarn__get_queue_user_acls_info_response_proto__pack
                     (const Hadoop__Yarn__GetQueueUserAclsInfoResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_queue_user_acls_info_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetQueueUserAclsInfoResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetQueueUserAclsInfoResponseProto *
       hadoop__yarn__get_queue_user_acls_info_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_queue_user_acls_info_response_proto__free_unpacked
                     (Hadoop__Yarn__GetQueueUserAclsInfoResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StartContainerRequestProto methods */
void   hadoop__yarn__start_container_request_proto__init
                     (Hadoop__Yarn__StartContainerRequestProto         *message);
size_t hadoop__yarn__start_container_request_proto__get_packed_size
                     (const Hadoop__Yarn__StartContainerRequestProto   *message);
size_t hadoop__yarn__start_container_request_proto__pack
                     (const Hadoop__Yarn__StartContainerRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__start_container_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__StartContainerRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StartContainerRequestProto *
       hadoop__yarn__start_container_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__start_container_request_proto__free_unpacked
                     (Hadoop__Yarn__StartContainerRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StartContainerResponseProto methods */
void   hadoop__yarn__start_container_response_proto__init
                     (Hadoop__Yarn__StartContainerResponseProto         *message);
size_t hadoop__yarn__start_container_response_proto__get_packed_size
                     (const Hadoop__Yarn__StartContainerResponseProto   *message);
size_t hadoop__yarn__start_container_response_proto__pack
                     (const Hadoop__Yarn__StartContainerResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__start_container_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__StartContainerResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StartContainerResponseProto *
       hadoop__yarn__start_container_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__start_container_response_proto__free_unpacked
                     (Hadoop__Yarn__StartContainerResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StopContainerRequestProto methods */
void   hadoop__yarn__stop_container_request_proto__init
                     (Hadoop__Yarn__StopContainerRequestProto         *message);
size_t hadoop__yarn__stop_container_request_proto__get_packed_size
                     (const Hadoop__Yarn__StopContainerRequestProto   *message);
size_t hadoop__yarn__stop_container_request_proto__pack
                     (const Hadoop__Yarn__StopContainerRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__stop_container_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__StopContainerRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StopContainerRequestProto *
       hadoop__yarn__stop_container_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__stop_container_request_proto__free_unpacked
                     (Hadoop__Yarn__StopContainerRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StopContainerResponseProto methods */
void   hadoop__yarn__stop_container_response_proto__init
                     (Hadoop__Yarn__StopContainerResponseProto         *message);
size_t hadoop__yarn__stop_container_response_proto__get_packed_size
                     (const Hadoop__Yarn__StopContainerResponseProto   *message);
size_t hadoop__yarn__stop_container_response_proto__pack
                     (const Hadoop__Yarn__StopContainerResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__stop_container_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__StopContainerResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StopContainerResponseProto *
       hadoop__yarn__stop_container_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__stop_container_response_proto__free_unpacked
                     (Hadoop__Yarn__StopContainerResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetContainerStatusRequestProto methods */
void   hadoop__yarn__get_container_status_request_proto__init
                     (Hadoop__Yarn__GetContainerStatusRequestProto         *message);
size_t hadoop__yarn__get_container_status_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetContainerStatusRequestProto   *message);
size_t hadoop__yarn__get_container_status_request_proto__pack
                     (const Hadoop__Yarn__GetContainerStatusRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_container_status_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetContainerStatusRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetContainerStatusRequestProto *
       hadoop__yarn__get_container_status_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_container_status_request_proto__free_unpacked
                     (Hadoop__Yarn__GetContainerStatusRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetContainerStatusResponseProto methods */
void   hadoop__yarn__get_container_status_response_proto__init
                     (Hadoop__Yarn__GetContainerStatusResponseProto         *message);
size_t hadoop__yarn__get_container_status_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetContainerStatusResponseProto   *message);
size_t hadoop__yarn__get_container_status_response_proto__pack
                     (const Hadoop__Yarn__GetContainerStatusResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_container_status_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetContainerStatusResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetContainerStatusResponseProto *
       hadoop__yarn__get_container_status_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_container_status_response_proto__free_unpacked
                     (Hadoop__Yarn__GetContainerStatusResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StartContainersRequestProto methods */
void   hadoop__yarn__start_containers_request_proto__init
                     (Hadoop__Yarn__StartContainersRequestProto         *message);
size_t hadoop__yarn__start_containers_request_proto__get_packed_size
                     (const Hadoop__Yarn__StartContainersRequestProto   *message);
size_t hadoop__yarn__start_containers_request_proto__pack
                     (const Hadoop__Yarn__StartContainersRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__start_containers_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__StartContainersRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StartContainersRequestProto *
       hadoop__yarn__start_containers_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__start_containers_request_proto__free_unpacked
                     (Hadoop__Yarn__StartContainersRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__ContainerExceptionMapProto methods */
void   hadoop__yarn__container_exception_map_proto__init
                     (Hadoop__Yarn__ContainerExceptionMapProto         *message);
size_t hadoop__yarn__container_exception_map_proto__get_packed_size
                     (const Hadoop__Yarn__ContainerExceptionMapProto   *message);
size_t hadoop__yarn__container_exception_map_proto__pack
                     (const Hadoop__Yarn__ContainerExceptionMapProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__container_exception_map_proto__pack_to_buffer
                     (const Hadoop__Yarn__ContainerExceptionMapProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__ContainerExceptionMapProto *
       hadoop__yarn__container_exception_map_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__container_exception_map_proto__free_unpacked
                     (Hadoop__Yarn__ContainerExceptionMapProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StartContainersResponseProto methods */
void   hadoop__yarn__start_containers_response_proto__init
                     (Hadoop__Yarn__StartContainersResponseProto         *message);
size_t hadoop__yarn__start_containers_response_proto__get_packed_size
                     (const Hadoop__Yarn__StartContainersResponseProto   *message);
size_t hadoop__yarn__start_containers_response_proto__pack
                     (const Hadoop__Yarn__StartContainersResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__start_containers_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__StartContainersResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StartContainersResponseProto *
       hadoop__yarn__start_containers_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__start_containers_response_proto__free_unpacked
                     (Hadoop__Yarn__StartContainersResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StopContainersRequestProto methods */
void   hadoop__yarn__stop_containers_request_proto__init
                     (Hadoop__Yarn__StopContainersRequestProto         *message);
size_t hadoop__yarn__stop_containers_request_proto__get_packed_size
                     (const Hadoop__Yarn__StopContainersRequestProto   *message);
size_t hadoop__yarn__stop_containers_request_proto__pack
                     (const Hadoop__Yarn__StopContainersRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__stop_containers_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__StopContainersRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StopContainersRequestProto *
       hadoop__yarn__stop_containers_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__stop_containers_request_proto__free_unpacked
                     (Hadoop__Yarn__StopContainersRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__StopContainersResponseProto methods */
void   hadoop__yarn__stop_containers_response_proto__init
                     (Hadoop__Yarn__StopContainersResponseProto         *message);
size_t hadoop__yarn__stop_containers_response_proto__get_packed_size
                     (const Hadoop__Yarn__StopContainersResponseProto   *message);
size_t hadoop__yarn__stop_containers_response_proto__pack
                     (const Hadoop__Yarn__StopContainersResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__stop_containers_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__StopContainersResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__StopContainersResponseProto *
       hadoop__yarn__stop_containers_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__stop_containers_response_proto__free_unpacked
                     (Hadoop__Yarn__StopContainersResponseProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetContainerStatusesRequestProto methods */
void   hadoop__yarn__get_container_statuses_request_proto__init
                     (Hadoop__Yarn__GetContainerStatusesRequestProto         *message);
size_t hadoop__yarn__get_container_statuses_request_proto__get_packed_size
                     (const Hadoop__Yarn__GetContainerStatusesRequestProto   *message);
size_t hadoop__yarn__get_container_statuses_request_proto__pack
                     (const Hadoop__Yarn__GetContainerStatusesRequestProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_container_statuses_request_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetContainerStatusesRequestProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetContainerStatusesRequestProto *
       hadoop__yarn__get_container_statuses_request_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_container_statuses_request_proto__free_unpacked
                     (Hadoop__Yarn__GetContainerStatusesRequestProto *message,
                      ProtobufCAllocator *allocator);
/* Hadoop__Yarn__GetContainerStatusesResponseProto methods */
void   hadoop__yarn__get_container_statuses_response_proto__init
                     (Hadoop__Yarn__GetContainerStatusesResponseProto         *message);
size_t hadoop__yarn__get_container_statuses_response_proto__get_packed_size
                     (const Hadoop__Yarn__GetContainerStatusesResponseProto   *message);
size_t hadoop__yarn__get_container_statuses_response_proto__pack
                     (const Hadoop__Yarn__GetContainerStatusesResponseProto   *message,
                      uint8_t             *out);
size_t hadoop__yarn__get_container_statuses_response_proto__pack_to_buffer
                     (const Hadoop__Yarn__GetContainerStatusesResponseProto   *message,
                      ProtobufCBuffer     *buffer);
Hadoop__Yarn__GetContainerStatusesResponseProto *
       hadoop__yarn__get_container_statuses_response_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hadoop__yarn__get_container_statuses_response_proto__free_unpacked
                     (Hadoop__Yarn__GetContainerStatusesResponseProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hadoop__Yarn__RegisterApplicationMasterRequestProto_Closure)
                 (const Hadoop__Yarn__RegisterApplicationMasterRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__RegisterApplicationMasterResponseProto_Closure)
                 (const Hadoop__Yarn__RegisterApplicationMasterResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__FinishApplicationMasterRequestProto_Closure)
                 (const Hadoop__Yarn__FinishApplicationMasterRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__FinishApplicationMasterResponseProto_Closure)
                 (const Hadoop__Yarn__FinishApplicationMasterResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__AllocateRequestProto_Closure)
                 (const Hadoop__Yarn__AllocateRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__NMTokenProto_Closure)
                 (const Hadoop__Yarn__NMTokenProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__AllocateResponseProto_Closure)
                 (const Hadoop__Yarn__AllocateResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetNewApplicationRequestProto_Closure)
                 (const Hadoop__Yarn__GetNewApplicationRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetNewApplicationResponseProto_Closure)
                 (const Hadoop__Yarn__GetNewApplicationResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetApplicationReportRequestProto_Closure)
                 (const Hadoop__Yarn__GetApplicationReportRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetApplicationReportResponseProto_Closure)
                 (const Hadoop__Yarn__GetApplicationReportResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__SubmitApplicationRequestProto_Closure)
                 (const Hadoop__Yarn__SubmitApplicationRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__SubmitApplicationResponseProto_Closure)
                 (const Hadoop__Yarn__SubmitApplicationResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__KillApplicationRequestProto_Closure)
                 (const Hadoop__Yarn__KillApplicationRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__KillApplicationResponseProto_Closure)
                 (const Hadoop__Yarn__KillApplicationResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetClusterMetricsRequestProto_Closure)
                 (const Hadoop__Yarn__GetClusterMetricsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetClusterMetricsResponseProto_Closure)
                 (const Hadoop__Yarn__GetClusterMetricsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetApplicationsRequestProto_Closure)
                 (const Hadoop__Yarn__GetApplicationsRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetApplicationsResponseProto_Closure)
                 (const Hadoop__Yarn__GetApplicationsResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetClusterNodesRequestProto_Closure)
                 (const Hadoop__Yarn__GetClusterNodesRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetClusterNodesResponseProto_Closure)
                 (const Hadoop__Yarn__GetClusterNodesResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetQueueInfoRequestProto_Closure)
                 (const Hadoop__Yarn__GetQueueInfoRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetQueueInfoResponseProto_Closure)
                 (const Hadoop__Yarn__GetQueueInfoResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetQueueUserAclsInfoRequestProto_Closure)
                 (const Hadoop__Yarn__GetQueueUserAclsInfoRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetQueueUserAclsInfoResponseProto_Closure)
                 (const Hadoop__Yarn__GetQueueUserAclsInfoResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StartContainerRequestProto_Closure)
                 (const Hadoop__Yarn__StartContainerRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StartContainerResponseProto_Closure)
                 (const Hadoop__Yarn__StartContainerResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StopContainerRequestProto_Closure)
                 (const Hadoop__Yarn__StopContainerRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StopContainerResponseProto_Closure)
                 (const Hadoop__Yarn__StopContainerResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetContainerStatusRequestProto_Closure)
                 (const Hadoop__Yarn__GetContainerStatusRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetContainerStatusResponseProto_Closure)
                 (const Hadoop__Yarn__GetContainerStatusResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StartContainersRequestProto_Closure)
                 (const Hadoop__Yarn__StartContainersRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__ContainerExceptionMapProto_Closure)
                 (const Hadoop__Yarn__ContainerExceptionMapProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StartContainersResponseProto_Closure)
                 (const Hadoop__Yarn__StartContainersResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StopContainersRequestProto_Closure)
                 (const Hadoop__Yarn__StopContainersRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__StopContainersResponseProto_Closure)
                 (const Hadoop__Yarn__StopContainersResponseProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetContainerStatusesRequestProto_Closure)
                 (const Hadoop__Yarn__GetContainerStatusesRequestProto *message,
                  void *closure_data);
typedef void (*Hadoop__Yarn__GetContainerStatusesResponseProto_Closure)
                 (const Hadoop__Yarn__GetContainerStatusesResponseProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hadoop__yarn__register_application_master_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__register_application_master_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__finish_application_master_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__finish_application_master_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__allocate_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__nmtoken_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__allocate_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_new_application_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_new_application_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_application_report_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_application_report_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__submit_application_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__submit_application_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__kill_application_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__kill_application_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_cluster_metrics_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_cluster_metrics_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_applications_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_applications_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_cluster_nodes_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_cluster_nodes_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_queue_info_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_queue_info_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_queue_user_acls_info_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_queue_user_acls_info_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__start_container_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__start_container_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__stop_container_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__stop_container_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_container_status_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_container_status_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__start_containers_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__container_exception_map_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__start_containers_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__stop_containers_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__stop_containers_response_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_container_statuses_request_proto__descriptor;
extern const ProtobufCMessageDescriptor hadoop__yarn__get_container_statuses_response_proto__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_yarn_5fservice_5fprotos_2eproto__INCLUDED */
